Fixing bug sync to labkes
jabardigitalservice/pikobar-rapidtest-api pull request #121
Opened 2021-02-05 10:21 UTC by rachadiannovansyah

Overview :
- Penyesuaian payload ketika POST data ke Simlab
- Merapihkan code menggunakan phpcs dan phpfmt (extension vscode)
- Sudah concalling dgn programmer simlab (ayocoding) terkait keselarasan data

Note:
- Tested on postman data berhasil terkirim ke simlab

![image](https://user-images.githubusercontent.com/32012588/107021231-7778cd80-67d6-11eb-9688-ebe44b5cc947.png)

cc : mas @yohang88

2021-02-05 10:44 UTC, aldidoanta requested changes

2021-02-05 10:44 UTC, aldidoanta commented on app/Http/Controllers/SyncToLabkesController.php
> +                $response['result'] = ['succes' => $result->result->berhasil, 'failed' => $result->result->gagal];
Minor kang @rachadiannovansyah . Di dalam ` $response['result']`, harusnya nama field-nya `success` ya, bukan `succes`?

Kalau bagian ini diubah dari `succes` jadi `success`, di manlab berubah nggak kang @ayocodingit ?

2021-02-05 10:49 UTC, ayocodingit commented on app/Http/Controllers/SyncToLabkesController.php
> +                $response['result'] = ['succes' => $result->result->berhasil, 'failed' => $result->result->gagal];
Kalau dari manlab result berhasil dan result gagal kang . Nah untuk typo succes itu respon untuk di tes masifnya

2021-02-05 11:07 UTC, sandisunandar99 commented on app/Http/Controllers/SyncToLabkesController.php
> +                $response['result'] = ['succes' => $result->result->berhasil, 'failed' => $result->result->gagal];
typo kayanya,, wkwkwk

2021-02-05 11:12 UTC, yohang88 commented on app/Http/Controllers/SyncToLabkesController.php
> +                $response['result'] = ['succes' => $result->result->berhasil, 'failed' => $result->result->gagal];
tipo tipo 😁

2021-02-05 11:24 UTC, yohang88 commented on resources/lang/id/response.php
> +    'sync_failed' => ' gagal melakukan sinkronsiasi ke server tujuan',
sebaiknya spasi ditambahkan di saat mau menampilkan pesannya 😁 di language ini ga perlu pakai spasi 😁

2021-02-05 11:55 UTC, firmanJS approved these changes

2021-02-07 01:09 UTC, ayocodingit approved these changes

2021-02-08 01:11 UTC, rachadiannovansyah reviewed
Done fixing typo & remove unused spacing

2021-02-08 01:11 UTC, rachadiannovansyah commented on app/Http/Controllers/SyncToLabkesController.php
> +                $response['result'] = ['succes' => $result->result->berhasil, 'failed' => $result->result->gagal];
yapp betul typo kang @aldidoanta sudah diperbaiki, hatur nuhun kang :smile_cat:

2021-02-08 01:11 UTC, rachadiannovansyah commented on resources/lang/id/response.php
> +    'sync_failed' => ' gagal melakukan sinkronsiasi ke server tujuan',
done mas :sweat_smile:

2021-02-08 02:55 UTC, aldidoanta approved these changes

2021-02-08 02:57 UTC, merged