Change sorting daftar peserta
jabardigitalservice/pikobar-rapidtest-api pull request #124
Opened 2021-02-15 06:25 UTC by rachadiannovansyah

![image](https://user-images.githubusercontent.com/32012588/107912369-ff0dcb80-6f90-11eb-9f16-3622b36c3e08.png)

Overview:
- Tertinggal untuk filter cast by registration_date_start dan registration_date_end masih merefer ke created_at, harusnya saat ini merefer ke updated_at :smile: 

cc: mas @yohang88 :man_dancing:

2021-02-15 06:43 UTC, yohang88 approved these changes

2021-02-15 06:45 UTC, yohang88 requested changes
Btw ini konteksnya gimana ya? Kalau registrasi, bukannya sudah betul pakai `created_at` ? Karena kalau pakai `updated_at`, bagaimana jika ada data yang diupdate? Sorting tanggal registrasinya jadi geser?

2021-02-15 07:05 UTC, rachadiannovansyah commented
> Btw ini konteksnya gimana ya? Kalau registrasi, bukannya sudah betul pakai `created_at` ? Karena kalau pakai `updated_at`, bagaimana jika ada data yang diupdate? Sorting tanggal registrasinya jadi geser?

oooo ini 
![image](https://user-images.githubusercontent.com/32012588/107915330-e1436500-6f96-11eb-8dd9-0de5a60587d3.png)

cc kang @maruf12 :smile:

2021-02-15 07:14 UTC, maruf12 commented
> > Btw ini konteksnya gimana ya? Kalau registrasi, bukannya sudah betul pakai `created_at` ? Karena kalau pakai `updated_at`, bagaimana jika ada data yang diupdate? Sorting tanggal registrasinya jadi geser?
> 
> oooo ini
> ![image](https://user-images.githubusercontent.com/32012588/107915330-e1436500-6f96-11eb-8dd9-0de5a60587d3.png)
> 
> cc kang @maruf12 😄

@yohang88 nimbrung komen mas wkwk. Jadi kebutuhan dilapangan sekarang tanggal terdaftar mengacu ke `updated_at`. Ini karena data peserta yang udah terdaftar bisa daftar lagi, nah peserta tersebut kan tidak jadi double tapi akan meng-update data perserta lama ke peserta baru termasuk created_atnya juga isinya created_at ketika pertama daftar. Nah jadinya kalo yang ditampilkan di user masih `created_at` kasus peserta yang daftar kembali ini akan tertimpa di bawah. Makanya tadi ada kebutuhan sorting juga menggunakan `updated-at`. Dan tentunya filter yang `registration_date` juga harus merefer ke `updated_at` karena data yang ditampilkan user juga `updated_at`. Kalau `registration_date` masih merefer ke `created_at` nanti datanya tidak sesuai antara hasil filter sama yang ditampilkan di usernya.

2021-02-15 08:10 UTC, yohang88 commented
@maruf12 @rachadiannovansyah i see, jadi proses bisnisnya adalah:

1. Peserta registrasi baru, jika NIK-nya belum pernah terdaftar, sistem akan membuat user baru.
2. Peserta registrasi baru, tapi jika NIK-nya sudah pernah terdaftar, sistem akan update data existing.

Dua proses ini saya lihat ga ada di dokumentasi https://wiki.digitalservice.id/doc/proses-bisnis-hVaBQV5GTU ?

Menurut saya konteks `created_at` dan `updated_at` sebaiknya tidak boleh tercampur dengan faktor apakah sebuah user registrasi baru atau registrasi update existing.

Contoh yang disebutkan @maruf12 itu kan 1 proses, user registrasi, dia akan update ke record existing. Ini sudah benar.

Tapi coba lihat case ini:
1. User registrasi pertama bulan Desember 2020.
2. Hari ini (Februari) admin mengubah data peserta existing di dashboard, misal memperbaiki nama, alamat, artinya atribut `updated_at` juga akan *berubah*.

Maka pertanyaannya, `updated_at` ini berubah karena apa?
1. User registrasi tapi update data existing, atau
2. Admin mengubah detail record user?

2021-02-15 08:26 UTC, maruf12 commented
> @maruf12 @rachadiannovansyah i see, jadi proses bisnisnya adalah:
> 
> 1. Peserta registrasi baru, jika NIK-nya belum pernah terdaftar, sistem akan membuat user baru.
> 2. Peserta registrasi baru, tapi jika NIK-nya sudah pernah terdaftar, sistem akan update data existing.
> 
> Dua proses ini saya lihat ga ada di dokumentasi https://wiki.digitalservice.id/doc/proses-bisnis-hVaBQV5GTU ?
> 
> Menurut saya konteks `created_at` dan `updated_at` sebaiknya tidak boleh tercampur dengan faktor apakah sebuah user registrasi baru atau registrasi update existing.
> 
> Contoh yang disebutkan @maruf12 itu kan 1 proses, user registrasi, dia akan update ke record existing. Ini sudah benar.
> 
> Tapi coba lihat case ini:
> 
> 1. User registrasi pertama bulan Desember 2020.
> 2. Hari ini (Februari 2021) admin mengubah data peserta existing di dashboard, misal memperbaiki nama, alamat, artinya atribut `updated_at` juga akan **berubah** menjadi hari ini.
> 
> Jika di-sort berdasar tanggal registrasi, maka user ini jadi paling atas? Kan `updated_at`-nya berubah jadi hari ini.
> 
> Tentu ini tidak valid, karena user registrasi di bulan Desember 2020.
> 
> Maka pertanyaannya, `updated_at` ini berubah karena apa?
> 
> 1. User registrasi tapi update data existing, atau
> 2. Admin mengubah detail record user?

@yohang88 @rachadiannovansyah Yes betul ketika ada update detail record pada user maka `upadated_at` nya akan berubah.
Lalu untuk solusinya apakah sebaiknya tanggal daftar ini dipisahkan tersendiri, jadi tidak bergantung ke `created_at` dan `updated_at` juga?

2021-02-15 08:55 UTC, rachadiannovansyah commented
> @maruf12 @rachadiannovansyah i see, jadi proses bisnisnya adalah:
> 
> 1. Peserta registrasi baru, jika NIK-nya belum pernah terdaftar, sistem akan membuat user baru.
> 2. Peserta registrasi baru, tapi jika NIK-nya sudah pernah terdaftar, sistem akan update data existing.
> 
> Dua proses ini saya lihat ga ada di dokumentasi https://wiki.digitalservice.id/doc/proses-bisnis-hVaBQV5GTU ?
> 
> Menurut saya konteks `created_at` dan `updated_at` sebaiknya tidak boleh tercampur dengan faktor apakah sebuah user registrasi baru atau registrasi update existing.
> 
> Contoh yang disebutkan @maruf12 itu kan 1 proses, user registrasi, dia akan update ke record existing. Ini sudah benar.
> 
> Tapi coba lihat case ini:
> 
> 1. User registrasi pertama bulan Desember 2020.
> 2. Hari ini (Februari 2021) admin mengubah data peserta existing di dashboard, misal memperbaiki nama, alamat, artinya atribut `updated_at` juga akan **berubah** menjadi hari ini.
> 
> Jika di-sort berdasar tanggal registrasi, maka user ini jadi paling atas? Kan `updated_at`-nya berubah jadi hari ini.
> 
> Tentu ini tidak valid, karena user registrasi di bulan Desember 2020.
> 
> Maka pertanyaannya, `updated_at` ini berubah karena apa?
> 
> 1. User registrasi tapi update data existing, atau
> 2. Admin mengubah detail record user?

nah iya cons nya jika ada record yg di edit record tsb akan ikut ke update, tapi prosnya betul seperti yg dikatakan kang @maruf12 ini merupakan request dr lapangan ketika ada user yang dulunya sudah ada, lalu ikut lagi pendaftaran.. menarik untuk dibahas sih ini, terutama jika dikaitkan dgn aspek probis perlu ditanyakan lg mungkin dgn mas Tofhan, namun jika melihat dr aspek konsistensi data ini tentu kurang bagus namun dapat memenuhi kebutuhan saat ini.. cmiiw mas @yohang88

2021-02-15 10:56 UTC, sandisunandar99 commented
kayanya pertanyaannya bkal sama sih kenapa terkait sorting pake update_at, soalnya ketika user itu update maka otomatis akan up ke atas dan tanggal kapan registrasi nya pun akan berubah pas dilihat di FE. tapi kalo konteksnya unutk list user dan untuk mengecek siapa user terakhir yang diupdate .. is fine aja wkwkwk :smile_cat:  
cmiwiw jika komen nya sedikit ngelantur,, wkwkwk :laughing: :rofl:

2021-02-15 11:05 UTC, yohang88 commented
Yup bener banget mamang @sandisunandar99 😁 👍 

Kalau untuk konteks list user, sort by paling terakhir update, maka relevan pakai `updated_at` 😁 

Problemnya ini konteksnya/maknanya beda, tanggal registrasi pasti berbeda dengan `created_at` dan `updated_at`.

Mangga dipertimbangkan pros & cons (effort & impact) masing-masing:
1. Tetap pakai `updated_at` (PR ini dimerge). Tapi tolong catat ini jadi technical debt, next harus diperbaiki. Karena akan ada potensi salah informasi (use case yang aku tulis di reply atas).
2. Bikin kolom baru, `registered_at`. Ini perlu migrasi, karena data-data yang udah lama nilainya akan NULL, sehingga perlu diset value `UPDATE table SET registered_at = created_at` dulu.

@rachadiannovansyah @maruf12 tetap tenang 😁

2021-02-16 04:21 UTC, yohang88 approved these changes

2021-02-16 04:21 UTC, merged