add validation when kode sample already exists or used
jabardigitalservice/pikobar-rapidtest-api pull request #125
Opened 2021-02-15 10:29 UTC by rachadiannovansyah

--Expected result--
![image](https://user-images.githubusercontent.com/32012588/107934544-c848ad00-6fb2-11eb-9974-409dfbde28d4.png)

--Actual result (kode sample bisa sama alias duplikat) --
![image](https://user-images.githubusercontent.com/32012588/107934568-d1397e80-6fb2-11eb-86d9-721c9888616b.png)

Overview:
- Menambahkan sedikit logic untuk memvalidasi kode sample jika sudah pernah digunakan atau sama
- Menggunakan HTTP_Response sebagai return code http agar mudah dimengerti oleh programmer lain (biasanya hanya melemparkan nomor http kodenya (400 untuk bad request))

Note:
- Tested

cc mas @yohang88 @sandisunandar99

2021-02-15 10:46 UTC, sandisunandar99 commented on app/Http/Controllers/Rdt/RdtEventParticipantSetLabCodeController.php
> +        if (RdtInvitation::query()->where('lab_code_sample', $request->input('lab_code_sample'))->count() > 0) {
#ASK
mang @rachadiannovansyah yg ini mu tanya, untuk code sample dibuat runut ya? bukan di buat unique number ?

2021-02-15 10:51 UTC, rachadiannovansyah commented on app/Http/Controllers/Rdt/RdtEventParticipantSetLabCodeController.php
> +        if (RdtInvitation::query()->where('lab_code_sample', $request->input('lab_code_sample'))->count() > 0) {
iya kang kode sample dimasukin manual oleh petugas alias tidak otomatis :D

2021-02-15 10:59 UTC, yohang88 requested changes
Minor check @rachadiannovansyah 😁 👍

2021-02-15 10:59 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtEventParticipantSetLabCodeController.php
> +        if (RdtInvitation::query()->where('lab_code_sample', $request->input('lab_code_sample'))->count() > 0) {
Agar lebih manusiawi/mudah dibaca, coba pisahkan dengan variable-variable dulu 😁 

Contoh:
```php
$inputLabCodeSample = $request->input('lab_code_sample');
$labCodeSampleCount = RdtInvitation::query()->where('lab_code_sample', $inputLabCodeSample)->count();

if ($labCodeSampleCount > 0) {
    return "blablabla";
}

```

Lebih banyak baris memang, tapi kira-kira lebih mudah dipahami yang mana? 😁 

Btw penasaran juga, kalau ini pakai Form Request untuk validasi apakah udah ada datanya (exist), bisa ga ya? 🤔

2021-02-15 11:04 UTC, sandisunandar99 approved these changes

2021-02-15 22:54 UTC, rachadiannovansyah commented
ooo i see, bagusnya taro dulu di variable agar lebih mudah dipahami yesss :dancers: 
done mas @yohang88 :smile:

2021-02-17 03:19 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtEventParticipantSetLabCodeController.php
> +        $labCodeSampleCount = RdtInvitation::query()->where('lab_code_sample', $inputCodeSample)->count();
@rachadiannovansyah jika kode sampel sama tapi beda event/kegiatan test, bagaimana? Tetap ga boleh dipakai? 😁

2021-02-17 03:45 UTC, rachadiannovansyah commented on app/Http/Controllers/Rdt/RdtEventParticipantSetLabCodeController.php
> +        $labCodeSampleCount = RdtInvitation::query()->where('lab_code_sample', $inputCodeSample)->count();
hmmmm menarik, thanks for correct mas @yohang88 :smile: 
stelah ku coba konfirmasi mas Thofan ternyata yapp kode sample bisa sama namun di kegiatan berbeda, miss understanding kmren ku kira 'unique' :+1: 

ku perbaiki dlu logicnya mas :+1:

2021-02-17 04:16 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtEventParticipantSetLabCodeController.php
> +        $labCodeSampleCount = RdtInvitation::query()->where('lab_code_sample', $inputCodeSample)->count();
Sheep, request diperjelas aja acceptance criterianya ke depan 😁

2021-02-22 02:27 UTC, rachadiannovansyah reviewed
sudah diperbaiki, boleh di check lagi mas @yohang88 :grin: :rocket:

2021-02-22 02:34 UTC, yohang88 approved these changes

2021-02-22 02:34 UTC, merged