add field status on simlab to received status integrasi peserta
jabardigitalservice/pikobar-rapidtest-api pull request #127
Opened 2021-02-16 12:05 UTC by rachadiannovansyah

![image](https://user-images.githubusercontent.com/32012588/108060476-80e12000-7089-11eb-80c1-63b7f748270e.png)

Link task on trello : https://trello.com/c/xMp7UHJd

Overview:
- Menambahkan field migrasi baru bernama 'status_on_simlab' di tabel invitation
- Mengupdate field tersebut pada setiap record yang sukses terkirim maupun yang gagal terkirim ( untuk memudahkan frontend mensortir peserta yang sudah terkirim atau gagal terkirim)
- Response payload sudah menyertakan status setiap peserta

Note:
- Tested

cc mas @yohang88 :smiling_face_with_three_hearts:

2021-02-17 03:22 UTC, yohang88 requested changes
Cek minor 😁

2021-02-17 03:22 UTC, yohang88 commented on app/Http/Controllers/SyncToLabkesController.php
> +                ->update(['synchronization_at' => now(), 'status_on_simlab' => 'SENT']);
Apa bedanya dengan kolom `synchronization_at` ? Coba dicek, field `synchronization_at` ini diisi saat hanya berhasil kan? 

Kalau berhasil, `synchronization_at` diisi timestamp saat berhasil.
Kalau gagla, `synchronization_at` akan tetap null.

Sehingga dari kolom `synchronization_at` ini harusnya bisa dipakai untuk check apakah sebuah record berhasil dikirim ke SIM Lab atau tidak.

2021-02-17 03:58 UTC, rachadiannovansyah commented on app/Http/Controllers/SyncToLabkesController.php
> +                ->update(['synchronization_at' => now(), 'status_on_simlab' => 'SENT']);
Yuppp betul mas, tapi apakah `synchronization_at` bisa menampung informasi data yang gagal terkirim ke simlab mas @yohang88 ? :cmiiw
soalnya kmren FE request butuh status simlab tsb untuk marking data di list applicant jika ada peserta yang gagal terkirim datanya.. jadi dibuatlah field 'status_on_simlab' ini sebagai acuan nantinya di FE.
jadi nanti ada 3 kondisi yang bisa didapatkan FE untuk mengklasifikasikan data nya:
1. Gagal -> valuenya 'FAILED'
2. Terkirim -> valuenya 'SENT'
3. Belum dikirim -> valuenya masih 'NULL'

2021-02-17 04:15 UTC, yohang88 commented on app/Http/Controllers/SyncToLabkesController.php
> +                ->update(['synchronization_at' => now(), 'status_on_simlab' => 'SENT']);
Coba ditanyakan ke tim SIM Lab, balikannya apa ya? Ada reponse gagal gitu? 😁

2021-02-17 05:15 UTC, ayocodingit commented on app/Http/Controllers/SyncToLabkesController.php
> +                ->update(['synchronization_at' => now(), 'status_on_simlab' => 'SENT']);
![image](https://user-images.githubusercontent.com/41193120/108159461-b2093100-7119-11eb-8801-de8ca30e38e4.png)
example response gagalnya seperti ini mas

2021-02-18 01:45 UTC, rachadiannovansyah commented on app/Http/Controllers/SyncToLabkesController.php
> +                ->update(['synchronization_at' => now(), 'status_on_simlab' => 'SENT']);
up up  mas @yohang88 :smiling_face_with_three_hearts:

2021-02-18 03:26 UTC, yohang88 commented on app/Http/Controllers/SyncToLabkesController.php
> +                ->update(['synchronization_at' => now(), 'status_on_simlab' => 'SENT']);
Ok jadi memang ada balikan gagal dari SIM Lab ya @ayocodingit 👍 

@rachadiannovansyah Tapi pertanyaanku tetap sih, yang gagal `FAIELD` terus mau diapain? 😁 Hanya muncul di frontend / list table "Gagal" ? Menurut saya ini ga informatif 😁 Terus yang gagal harus diperbaiki, atau bisa dikirim ulang?

2021-02-18 03:36 UTC, rachadiannovansyah commented on app/Http/Controllers/SyncToLabkesController.php
> +                ->update(['synchronization_at' => now(), 'status_on_simlab' => 'SENT']);
okee mas @yohang88 ,  payload data  yg gagal ini tentu dibutuhkan kang maruf buat marking data peserta di list nya, untuk selanjutnya data peserta tersebut dicek dan diperbaiki, lalu dikirim ulang lagi..

cc: kang @maruf12 bisi ada yg kurang tersampaikan kang wkwk

2021-02-18 03:43 UTC, maruf12 commented on app/Http/Controllers/SyncToLabkesController.php
> +                ->update(['synchronization_at' => now(), 'status_on_simlab' => 'SENT']);
@yohang88 @rachadiannovansyah ikut nimbrung mas wkwk. Di FE ada permintaan data yang gagal di marking dengan cara di warnain di baris tablenya mas. Jadi setiap data pasien yang gagal dia akan ada warnanya biar admin lebih aware gitu. Nah kalo misalnya ini ngambil data dari `syncronization_at` yang `null` tentu ini kan bercampur dengan data yang belum dikirim. gitu sih 😁

2021-02-18 04:51 UTC, yohang88 commented on app/Http/Controllers/SyncToLabkesController.php
> +                ->update(['synchronization_at' => now(), 'status_on_simlab' => 'SENT']);
@rachadiannovansyah @maruf12 Kan di database backend ga disimpan keterangan gagalnya kenapa 😁 Terus bagaimana admin bisa tahu gagal dan apalagi bisa memperbaiki? 😁

2021-02-19 04:09 UTC, rachadiannovansyah commented on app/Http/Controllers/SyncToLabkesController.php
> +                ->update(['synchronization_at' => now(), 'status_on_simlab' => 'SENT']);
by the way mas @yohang88  message gagalnya kan didapat dari response API simlab (yg firman kasih diatas :grin: ) lalu oleh FE ditampilkan ke admin (respon gagalnya) sehingga admin aware terhadap data peserta yg gagal nya karna apa dan nge marking setiap user yang gagal ke kirim data nya.. gitu sih mas :grin: 

atau kalo dibutuhkan concal boleh mas sebentar :grin:

2021-02-19 06:38 UTC, yohang88 approved these changes

2021-02-19 06:38 UTC, merged