integrasi pendaftaran jenis rujukan
jabardigitalservice/pikobar-rapidtest-api pull request #138
Opened 2021-03-17 09:34 UTC by rachadiannovansyah

Refer to task --> https://trello.com/c/NJze8owN

Overview:
- Menambahkan field jenis_registrasi pada kegiatan
- Penyesuaian endpoint API integrasi simlab

Note:
- Tested

cc: mas @yohang88

2021-03-17 11:46 UTC, aldidoanta approved these changes

2021-03-17 17:26 UTC, yohang88 requested changes
Cek minor gans

2021-03-17 17:26 UTC, yohang88 commented on app/Enums/JenisRegistrasi.php
> +    public static function rujukan(): JenisRegistrasi
Ini kenapa dibuat seperti? Bukannya cukup pakai annotate?

2021-03-17 17:26 UTC, yohang88 commented on app/Http/Controllers/SyncToLabkesController.php
> +                'jenis_registrasi' => $rdtEvent->jenis_registrasi->getValue(),
Bagaimana jika kondisi field null?

2021-03-17 22:57 UTC, rachadiannovansyah commented on app/Enums/JenisRegistrasi.php
> +    public static function rujukan(): JenisRegistrasi
tidak mas, kemaren sudah coba pake anotate namun kesulitan nge-get value dari enumnya :grin: CMIIW

2021-03-17 23:02 UTC, rachadiannovansyah commented on app/Http/Controllers/SyncToLabkesController.php
> +                'jenis_registrasi' => $rdtEvent->jenis_registrasi->getValue(),
Ooo i see, sepertinya jika case yg skrg tidak akan null mas, karna jenis registrasi itu muncul ketika membuat kegiatan, jadi nantinya setiap kegiatan pasti memiliki value dari jenis registrasi nya :grin: 

oiya bagian validate nya ku masih taro nullable ya  :smile:

2021-03-17 23:11 UTC, rachadiannovansyah commented
sudah di update ya mas @yohang88 :grin:

2021-03-19 04:03 UTC, yohang88 commented on app/Enums/JenisRegistrasi.php
> +    public static function rujukan(): JenisRegistrasi
eh ga paham, ga bisa ngeget value gimana? ini nyambung ke sini?
```php
'jenis_registrasi' => $rdtEvent->jenis_registrasi->getValue(),
```

Itu bukannya cukup pakai `$rdtEvent->jenis_registrasi` udah dapat valuenya? 🤔

2021-03-19 04:20 UTC, rachadiannovansyah commented on app/Enums/JenisRegistrasi.php
> +    public static function rujukan(): JenisRegistrasi
nah nyoba pakai langsung pointer kaya `$rdtEvent->jenis_registrasi` hasilnya gini mas :grin: 

![image](https://user-images.githubusercontent.com/32012588/111730803-bd7c8300-88a4-11eb-97fa-d365ff9c3497.png)

kalo langsung di rujuk ke property value nya sperti ini `$rdtEvent->jenis_registrasi->value` error mas :grin: 

akhirnya pake cara buat value ini :grin:

2021-03-19 08:38 UTC, yohang88 approved these changes

2021-03-19 08:38 UTC, merged