add registration type to payload response
jabardigitalservice/pikobar-rapidtest-api pull request #142
Opened 2021-03-25 04:24 UTC by rachadiannovansyah

Refer to task --> https://trello.com/c/Zvnx3H1l

Overview:
- Make new variable to contains frequently used property objects
- Add `registration_type` into payload response

Note:
- Tested

cc: mas @yohang88

2021-03-25 10:13 UTC, sandisunandar99 commented on app/Http/Controllers/SyncToLabkesController.php
> +                'jenis_registrasi' => $type === null || $type === $mandiri ? $mandiri : $rujukan,
mau tanya terkait operator pada pengkondisian 
misal kaya yang diatas `if ($type != null)` dengan `$type === $mandiri`
operator yg di atas kan `"!=" `kalo misalkan kaya gini `"!==" `pengaruh ga ya?  atau `"===" `sama `"=="`

2021-03-25 10:39 UTC, rachadiannovansyah commented on app/Http/Controllers/SyncToLabkesController.php
> +                'jenis_registrasi' => $type === null || $type === $mandiri ? $mandiri : $rujukan,
ooowh oke kang, alesan ku pake "!=" pada kondisi awal itu memang hanya untuk checking value dari attribute nya null apa ngga, nah untuk yg comparison `$type === $mandiri` ini aku pake "===" agar buat nge check value dan data type nya sesuai apa ngga :grin: 
untuk pengaruh apa ngga, untuk case diatas aku coba mau "!=" ato "!==" gak berpengaruh apa2 kang @sandisunandar99 :grin: 

afaik, "==" dan "===" bedanya kalo yg two equals itu bandingin value nya tanpa liat tipe datanya, kalo yg three equals itu dia bandingin value nya dengan memperhatikan tipe datanya :grin:

2021-03-25 10:43 UTC, sandisunandar99 commented on app/Http/Controllers/SyncToLabkesController.php
> +                'jenis_registrasi' => $type === null || $type === $mandiri ? $mandiri : $rujukan,
Nah memang ga perlu di cek kesamaan type datanya y? Atau bebas aja yg penting value nya sma?

2021-03-25 10:54 UTC, rachadiannovansyah commented on app/Http/Controllers/SyncToLabkesController.php
> +                'jenis_registrasi' => $type === null || $type === $mandiri ? $mandiri : $rujukan,
bisa aja sih kang :grin: 
tapi iya mungkin perlu digunain three equals, walopun NULL value yg di attribute sekarang gamungkin string tapi lebih untuk minimalisis ada inject value string "null" yg iseng xixixi :grin:

2021-03-25 10:56 UTC, rachadiannovansyah commented
cek cek kang @sandisunandar99

2021-03-25 11:14 UTC, yohang88 commented on app/Http/Controllers/SyncToLabkesController.php
> +                'jenis_registrasi' => $type === null || $type === $mandiri ? $mandiri : $rujukan,
sheep betul masukannya @sandisunandar99 👍 Akan lebih baik dilakukan komparasi yang strict termasuk tipe datanya 😁

2021-03-25 11:15 UTC, yohang88 requested changes
Minor aja @rachadiannovansyah 👍 😁

2021-03-25 11:15 UTC, yohang88 commented on app/Http/Resources/RdtEventResource.php
> +        $selectedType = $type === null || $type === $mandiri ? $mandiri : $rujukan;
Imho menurut saya kondisional ini sulit dipahami, karena ada `OR ||`. Jadi ada berapa kondisional di sini ya? 1 atau 2 atau malah 3 ? 😁

2021-03-25 12:07 UTC, rachadiannovansyah commented on app/Http/Resources/RdtEventResource.php
> +        $selectedType = $type === null || $type === $mandiri ? $mandiri : $rujukan;
wkwkw okeee mas, disini tuh ada 2 kondisi untuk return true dan 1 kondisi untuk return false, yang dimana jika salah satu true maka proses dibawahnya dijalankan:
kondisi 1 -> jika $type nya null (mostly untuk data-data lama yg belum mempunyai value type) maka akan di anggap sebagai tes tipe mandiri
kondisi 2 -> ini untuk memperbaiki state logic sebelumnya yg asalnya `$type === null ? $mandiri : $rujukan;` aja, logic tsb akan miss kalo ada value $type yg berisi mandiri (otomatis `$type === null` nya akan return false) nah malah jadi dianggepnya rujukan karna masuk ke kondisi else :grin

kondisi elsenya -> tentu untuk mengisi value rujukan

jadi alternatifnya ku gunain OR untuk memenuhi salah satu kondisi tersebut :grin: 

ini juga hasil dri output PSR12 yg sebelumnya row code nya melebihi 120 :grinning: makanya ku pecah menjadi variabel2 terpisah dan gunain kondisional ternary :grin: 
cc mas @yohang88

2021-03-25 12:12 UTC, sandisunandar99 approved these changes

2021-03-25 12:32 UTC, ayocodingit commented on app/Http/Controllers/SyncToLabkesController.php
> +                'jenis_registrasi' => $type === null || $type === $mandiri ? $mandiri : $rujukan,
bagaimana jika `$type === null`  maka $type diisi dengan `mandiri` soalnya aku liat variable $type hanya digunakan sekali sisanya untuk melakukan pembanding saja #cwiiw

2021-03-25 12:33 UTC, ayocodingit commented on app/Http/Controllers/SyncToLabkesController.php
> +                'jenis_registrasi' => $type === null || $type === $mandiri ? $mandiri : $rujukan,
kang @rachadiannovansyah ,bagaimana jika $type === null maka $type diisi dengan mandiri soalnya aku liat variable $type hanya digunakan sekali sisanya untuk melakukan pembanding saja #cwiiw

2021-03-25 13:04 UTC, rachadiannovansyah commented on app/Http/Controllers/SyncToLabkesController.php
> +                'jenis_registrasi' => $type === null || $type === $mandiri ? $mandiri : $rujukan,
terimakasih sebelumnya masukannya kang @ayocodingit , tapi untuk case ini kita perlu mengecek value null atau tidak :grin: 
karena saat ini khususnya data existing yang sudah ada pasti value dari type nya ini null, maka dari itu dibuat kondisi `$type === null` untuk memastikan bahwa jika kondisi null tersebut akan masuk sebagai kategori mandiri :grin: 

jika hanya `$type === mandiri ` saja dan dilakukan pada row data yg memiliki value typenya null maka tidak akan ke cek alias akan masuk kondisi else yakni masuk ke rujukan, dan tentu ini bukan kondisi yg diinginkan karna data existing tersebut seharusnya masuk ke kategori tes mandiri. :grin:

2021-03-25 13:10 UTC, ayocodingit commented on app/Http/Controllers/SyncToLabkesController.php
> +                'jenis_registrasi' => $type === null || $type === $mandiri ? $mandiri : $rujukan,
Iya jika $type nya null itu artinya mandiri kan jadi set aja type nya menjadi mandiri 😁

2021-03-26 02:51 UTC, rachadiannovansyah reviewed
done, cek cekkk mas @yohang88 @ayocodingit :+1:

2021-03-26 03:24 UTC, ayocodingit approved these changes

2021-03-26 03:28 UTC, yohang88 approved these changes
Mantaapss @rachadiannovansyah

2021-03-26 03:28 UTC, merged