Update fitur f2 add heading section
jabardigitalservice/pikobar-rapidtest-api pull request #166
Opened 2021-04-30 04:06 UTC by rachadiannovansyah

Update requirement fitur Ekspor F2

Overview:
- Tambahan headers title berdasarkan lokasi dan tempat kegiatan
- Tested
![image](https://user-images.githubusercontent.com/32012588/116647171-195a2180-a9a4-11eb-9209-61acf6b3ab29.png)

cc: mas @yohang88 :rocket:

2021-04-30 04:34 UTC, yohang88 requested changes
Cek cek minor aja @rachadiannovansyah

2021-04-30 04:34 UTC, yohang88 commented on app/Exports/ParticipantListExport.php
> +            ["DINAS KESEHATAN : {$this->event->host_name}"],
Ini memangnya pasti harus ada Dinas Kesehatannya? Host Name ini ketentuan namanya seperti apa kah? Jangan-jangan dobel dobel DINAS KESEHATAN: Dinas Kesehatan Kota Bandung, misal.

2021-04-30 04:34 UTC, yohang88 commented on app/Exports/ParticipantListExport.php
> +        $this->date = Carbon::parse($event->end_at)
Ini date udah sesuai timezone yang dibutuhkan?

2021-04-30 06:13 UTC, rachadiannovansyah commented on app/Exports/ParticipantListExport.php
> +            ["DINAS KESEHATAN : {$this->event->host_name}"],
ahhh iya betul, ini ternyata menggunakan value kab/kota setelah di konfirmasi ke PM :+1: 
mkasih mas :+1:

2021-04-30 06:15 UTC, rachadiannovansyah commented on app/Exports/ParticipantListExport.php
> +        $this->date = Carbon::parse($event->end_at)
sudah diperbaiki mas :+1:

2021-04-30 06:15 UTC, rachadiannovansyah commented
cekcekkk mas @yohang88 :rocket:

2021-05-02 21:35 UTC, yohang88 commented on app/Exports/ParticipantListExport.php
> +    public function getDifferenceDays()
@rachadiannovansyah clean code pada intinya adalah yang self-decoumenting, bagaimana orang lain bisa memahami dengan mudah maksud dari sebuah code. Dan dari namingnya saya masih kurang paham untuk apa `getDifferenceDays()` ini? 😁

2021-05-02 22:22 UTC, rachadiannovansyah commented on app/Exports/ParticipantListExport.php
> +    public function getDifferenceDays()
sepertinya kurang `code block` nya yaaa untuk fungsi2 kondisional seperti ini agar mudah dipahami :grimacing: 

maksud dan tujuan dari dibuatkan fungsi ini sebetulnya hanya untuk menentukan kegiatan yang akan di eksport pada excel ini tuh apakah kegiatan harian atau untuk rentang waktu tertentu mas @yohang88 :+1:

2021-05-03 04:26 UTC, rachadiannovansyah commented
Contoh hasil tanggal:
1. Kegiatan yg berlangsung 1 hari
![image](https://user-images.githubusercontent.com/32012588/116834873-3f710300-abea-11eb-876e-3079b9cd410e.png)

2. Kegiatan yg berlangsung lebih dari 1 hari
![image](https://user-images.githubusercontent.com/32012588/116834892-4d268880-abea-11eb-97e6-92c626f1b970.png)

cc: mas @yohang88

2021-05-03 06:48 UTC, yohang88 approved these changes

2021-05-03 06:48 UTC, merged