Clean code code smell
jabardigitalservice/pikobar-rapidtest-api pull request #176
Opened 2021-05-20 06:14 UTC by rachadiannovansyah

Cicil clean code (code smell ) sedikit2 jadi bukit :smile: 

Overview:
- Fixing similar blocks of code (duplicate function)
- Fixing Code Complexity
- Remove if with [when](https://laravel.com/docs/7.x/helpers#method-fluent-str-when) :smile: 

Note:
- Re tested on Postman 

cc: mas @yohang88

2021-05-20 08:19 UTC, aldidoanta approved these changes

2021-05-21 14:02 UTC, yohang88 requested changes

2021-05-21 14:02 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtApplicantController.php
>          }
Penggunaan `when` ini menggantikan `if` adalah termasuk syntactic sugar ya, pemanis 😁  Namanya pemanis, suatu saat bikin enak, kondisi lain bikin sakit jika berlebihan 😛  Ini boleh didiskusikan ke tim backend coba. Kira-kira manakah yang lebih mudah dipahami untuk case ini, `IF` tradisional atau pakai `when()` ?

2021-05-21 14:28 UTC, rachadiannovansyah commented on app/Http/Controllers/Rdt/RdtApplicantController.php
>          }
Walaahhh wkwkwkwk okeee mas, tp balik lagi ke alasan awal penggunaan `when` ini sebenarnya untuk memperbaiki Code Smell yg terdeteksi, salah satunya untuk menghindari `Code Complexity` yg cukup kompleks dalam sebuah function (maksimal 5 kalo gasalah di aturan clean codenya itu)

Namun, kalo dari segi performance belum coba saya uji dengan penggunaan `if else` , tapi yg saya baca dari dokumentasi laravelnya `when` ini tetap tidak akan dijalankan jika argumen pertama (kondisinya) bernilai `false` mirip bgt dengan behavior `if else`, jadi asumsiku when ini tidak terlalu buruk untuk digunakan menggantikan peranan `if else `dalam kondisional query. Cmiiw 

Nemu juga beberapa insight juga dari bacaan 😄 :
![IMG_20210521_211020.jpg](https://user-images.githubusercontent.com/32012588/119152046-25ed0980-ba7a-11eb-9c96-35b1d49d2a92.jpg)

Tapi menarik sih dgn kalimat mas @yohang88 dimana `when` ini bisa bikin sakit jika digunakan berlebihan 😂😅

2021-06-07 08:15 UTC, rachadiannovansyah commented
berdasarkan diskusi yang kemarin di slack, kesimpulannya `when` akan tetap digunakan, namun jika ada case `when` dalam `when` (yg membuat sakit mata :smile: ) alternatifnya aku buatkan `protected function` agar tetap mudah dibaca,

commitan [terakhir](https://github.com/jabardigitalservice/pikobar-rapidtest-api/pull/176/commits/6e2e74bba8e7e73f4eb6b157d6f34cf0750e033b) udah aku coba test via postman dan berhasil :+1: 

cc: mas @yohang88 mohon reviewnya :grin:

2021-06-07 11:18 UTC, yohang88 approved these changes
Wokee sheep @rachadiannovansyah 👍

2021-06-07 11:19 UTC, merged