Add paging and search feature
jabardigitalservice/pikobar-rapidtest-api pull request #18
Opened 2020-09-01 10:30 UTC by nurisakbar

### Overview
Penambahan fitur paging dan searching pada rdt event check

CC : @yohang88 

### Related Task : 
https://trello.com/c/PmaYa0BQ/85-apk-scan-qr-belum-bisa-menarik-lebih-dari-1000-peserta-di-list-peserta

2020-09-01 10:42 UTC, yohang88 commented
- Seharusnya target branch PR-nya dalah branch `develop`, bukan `master` 😁 
- Saat ini belum perlu pakai versioning API, karena masih project kecil. Kalaupun akan pakai versioning, perlu diskusi untuk arsitekturnya dulu yes. Karena versioning tidak hanya sekedar menulis `v1`, `v2` 😁 
- Ini bukannya mau pakai solusi bikin endpoint dan controller baru untuk list peserta? Saya belum lihat ada kode ini, kecuali yang ada hanya source code yang sama dengan RdtEventCheckController existing.

2020-09-01 11:29 UTC, nurisakbar commented
>     * Seharusnya target branch PR-nya dalah branch `develop`, bukan `master` 😁
> 
>     * Saat ini belum perlu pakai versioning API, karena masih project kecil. Kalaupun akan pakai versioning, perlu diskusi untuk arsitekturnya dulu yes. Karena versioning tidak hanya sekedar menulis `v1`, `v2` 😁
> 
>     * Ini bukannya mau pakai solusi bikin endpoint dan controller baru untuk list peserta? Saya belum lihat ada kode ini, kecuali yang ada hanya source code yang sama dengan RdtEventCheckController existing.

ah iya bener, salah set target branch, soalnya yang dikasi contoh dari tadi kayak gitu.
berarti sekarang saya buat lagi aja ya :
Routing Method GET : /rdt/event/id/applicants , isinya cuman data peserta berdasarkan event yang bersangkutan.

2020-09-01 12:35 UTC, yohang88 commented
> > ```
> > * Seharusnya target branch PR-nya dalah branch `develop`, bukan `master` 😁
> > 
> > * Saat ini belum perlu pakai versioning API, karena masih project kecil. Kalaupun akan pakai versioning, perlu diskusi untuk arsitekturnya dulu yes. Karena versioning tidak hanya sekedar menulis `v1`, `v2` 😁
> > 
> > * Ini bukannya mau pakai solusi bikin endpoint dan controller baru untuk list peserta? Saya belum lihat ada kode ini, kecuali yang ada hanya source code yang sama dengan RdtEventCheckController existing.
> > ```
> 
> ah iya bener, salah set target branch, soalnya yang dikasi contoh dari tadi kayak gitu.
> berarti sekarang saya buat lagi aja ya :
> Routing Method GET : /rdt/event/id/applicants , isinya cuman data peserta berdasarkan event yang bersangkutan.

Untuk path routing, berhubung sudah ada `/rdt/events/:id/participants`, hati-hati namanya akan mirip kalau ada `/rdt/event/:id/applicants` 😁 

Usul saya: `/rdt/events/:id/participants/checkin`, gimana?

2020-09-01 13:22 UTC, nurisakbar commented
> > > ```
> > > * Seharusnya target branch PR-nya dalah branch `develop`, bukan `master` 😁
> > > 
> > > * Saat ini belum perlu pakai versioning API, karena masih project kecil. Kalaupun akan pakai versioning, perlu diskusi untuk arsitekturnya dulu yes. Karena versioning tidak hanya sekedar menulis `v1`, `v2` 😁
> > > 
> > > * Ini bukannya mau pakai solusi bikin endpoint dan controller baru untuk list peserta? Saya belum lihat ada kode ini, kecuali yang ada hanya source code yang sama dengan RdtEventCheckController existing.
> > > ```
> > 
> > 
> > ah iya bener, salah set target branch, soalnya yang dikasi contoh dari tadi kayak gitu.
> > berarti sekarang saya buat lagi aja ya :
> > Routing Method GET : /rdt/event/id/applicants , isinya cuman data peserta berdasarkan event yang bersangkutan.
> 
> Untuk path routing, berhubung sudah ada `/rdt/events/:id/participants`, hati-hati namanya akan mirip kalau ada `/rdt/event/:id/applicants` 😁
> 
> Usul saya: `/rdt/events/:id/participants/checkin`, gimana?

iya nih, kalau ngikutin seharusnya sih udah ada routing nya, oke siap pakai itu aja kalu gitu

2020-09-02 05:04 UTC, nurisakbar commented
kang @yohang88 , saya udah push perubahan terbaru tapi masih tanda silang pada total-coverage dan diff-coverage

2020-09-02 06:36 UTC, yohang88 requested changes
Minor revisi aja 😁 👍

2020-09-02 06:36 UTC, yohang88 commented on routes/api.php
> +Route::get('/rdt/events/{eventCode}/participants/checkin', 'Rdt\RdtEventParticipantsController');
Kode event atau `{eventCode}` itu memungkinkan adanya karakter `-`, `_`, sudah dicoba belum ya? Apakah akan error? Contoh: `PPM01-3278` Paling aman lebih baik event code ini ditangkap di dalam logic controller saja. Jadi di route path tidak perlu mengandung `id event`, `kode event`, dsb.

2020-09-02 06:36 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtEventParticipantsController.php
> +        $per_page  = $request->input('per_page', 50);
pakai standar penulisan variable `$camelCase` yak 😁

2020-09-02 06:36 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtEventParticipantsController.php
> +        return response()->json(['data' => $invitations->paginate($per_page)]);
Optimalkan pemakaian Resource https://laravel.com/docs/7.x/eloquent-resources agar attributnya bisa dikelola dari 1 tempat (serta jika ada kebutuhan field-field standard).

2020-09-02 06:37 UTC, yohang88 commented
> kang @yohang88 , saya udah push perubahan terbaru tapi masih tanda silang pada total-coverage dan diff-coverage

Gpp, test coverage saat ini optional saja. Kalau sempat bikin feature/unit test ya bagus, tapi kalau enggak ya gpp.

2020-09-02 06:58 UTC, nurisakbar commented on app/Http/Controllers/Rdt/RdtEventParticipantsController.php
> +        $per_page  = $request->input('per_page', 50);
siap udah di perbaiki yang ini

2020-09-02 07:01 UTC, nurisakbar commented on routes/api.php
> +Route::get('/rdt/events/{eventCode}/participants/checkin', 'Rdt\RdtEventParticipantsController');
berarti diganti menjadi method POST saja dan event_code nya dikirim dari parameter ?

2020-09-02 07:05 UTC, nurisakbar commented on app/Http/Controllers/Rdt/RdtEventParticipantsController.php
> +        return response()->json(['data' => $invitations->paginate($per_page)]);
untuk yang ini saya lihat udah ada RdtInvitationResource, tapi kebutuhan parresponse nya tidak sekompleks itu sehingga dengan pertimbangan performace saya fikir sebaiknya cukup dengan select field yang dibutuhkan saja kang, gimana kira kira ?

2020-09-02 08:37 UTC, yohang88 commented on routes/api.php
> +Route::get('/rdt/events/{eventCode}/participants/checkin', 'Rdt\RdtEventParticipantsController');
ok sepakat dengan method POST 😁

2020-09-02 08:44 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtEventParticipantsController.php
> +        return response()->json(['data' => $invitations->paginate($per_page)]);
@nurisakbar ah iya betul maaf maaf ini dipakai di app check-in ya.

1. Idenya saya sepakat untuk mengeluarkan response attributes yang dibutuhkan saja. Tinggal sekarang format struktur `data[]` itu agak sedikit diluar patternnya Laravel soalnya 😁 Karena kalau kita pakai `Resource`, format response `data`, `meta`, itu ada bentuknya sendiri. Kalau memang tidak bisa pakai existing class `RdtInvitationResource`, mungkin bisa bikin class Resource baru.

2. Sepertinya naming Controller `RdtEventParticipantsController` perlu diganti juga, karena mirip yang udah ada haha. Atau kayaknya kita perlu pisahin sementara dengan namespace `Controllers\Rdt\Checkin\ParticipantListController` ya, bagaimana? 😁

2020-09-02 09:57 UTC, nurisakbar commented on app/Http/Controllers/Rdt/RdtEventParticipantsController.php
> +        return response()->json(['data' => $invitations->paginate($per_page)]);
siap, udah saya perbaiki kang @yohang88 , mohon di review lagi

2020-09-03 00:28 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtEventParticipantsController.php
> +        return response()->json(['data' => $invitations->paginate($per_page)]);
Sip mantaaaps makasih banyak @nurisakbar 😁

2020-09-03 00:29 UTC, yohang88 approved these changes

2020-09-03 00:30 UTC, merged