Add validation import excel
jabardigitalservice/pikobar-rapidtest-api pull request #186
Opened 2021-06-21 10:46 UTC by rachadiannovansyah

Refer to task --> https://trello.com/c/J0rsD5LQ/289-validasi-import-hasil-tes

Overview:
- Fixing duplication code
- Add validation when importing data excel

Note:
- Tested on Postman

cc: mas @yohang88 @jabardigitalservice/jds-backend

2021-06-21 11:15 UTC, aldidoanta commented on app/Http/Controllers/Rdt/RdtEventParticipantImportResultController.php
>                      continue;
Karena di dalam `if` ada `continue`, jadinya `$rowsCount` harus ditulis di dalam `if` dan `else` ya?

2021-06-21 11:17 UTC, aldidoanta approved these changes

2021-06-21 11:21 UTC, rachadiannovansyah commented on app/Http/Controllers/Rdt/RdtEventParticipantImportResultController.php
>                      continue;
iyaap betul kang @aldidoanta :+1:

2021-06-21 11:21 UTC, ayocodingit approved these changes

2021-06-21 14:46 UTC, yohang88 requested changes

2021-06-21 14:46 UTC, yohang88 commented on app/Traits/ImportTrait.php
> +trait ImportTrait
Kenapa perlu dibuat `Trait` ?

**Bacaan:** 
https://www.php.net/manual/en/language.oop5.traits.php

> PHP implements a way to reuse code called Traits.
> 
> Traits are a mechanism for code reuse in single inheritance languages such as PHP. A Trait is intended to reduce some limitations of single inheritance by enabling a developer to reuse sets of methods freely in several independent classes living in different class hierarchies. The semantics of the combination of Traits and classes is defined in a way which reduces complexity, and avoids the typical problems associated with multiple inheritance and Mixins.

Yang di-highlight: reusable code, inheritance, several independent classes living in different class hierarchies

**Pertanyaan:**
Apakah `ImportTrait` ini memenuhi unsur penggunaan trait ini?

Jika 1 Trait ini hanya dipakai di 1 class, tentu tidak relevan menggunakan Trait ini 😁 

cc: @jabardigitalservice/jds-backend @sandisunandar99 @ayocodingit @rindibudiaramdhan @aldidoanta @rachadiannovansyah @khihadysucahyo @iprasetyaa @rizkyrmsyah

2021-06-21 15:09 UTC, rachadiannovansyah commented on app/Traits/ImportTrait.php
> +trait ImportTrait
Koreksi jika salah ya mas @yohang88 :smile:  Rencana ku pakai `Trait` ini untuk digunakan pada class lainnya (lebih dari 1 class), pun juga untuk menghindari duplication code.

kondisi saat ini memang `Trait` ini baru digunakan pada satu class saja (dalam PR ini), namun jika ku lihat pada codebasenya ada beberapa endpoint terkait import dan memungkinan `Trait` ini akan digunakan untuk melakukan validasi import.

2021-06-21 15:24 UTC, yohang88 commented on app/Traits/ImportTrait.php
> +trait ImportTrait
**YAGNI (You Aren’t Gonna Need It)**

https://betterprogramming.pub/kiss-dry-and-code-principles-every-developer-should-follow-b77d89f51d74

Sampai udah ada requierement kebutuhan validasi import yang lain: YAGNI 😛

Dibuat reusable saat memang udah jelas ada kebutuhan, ada pola duplikasi code, dsb. Jangan-jangan yang import baru nanti metodenya beda, validasi beda, dsb.

2021-06-21 15:30 UTC, rachadiannovansyah commented on app/Traits/ImportTrait.php
> +trait ImportTrait
Ahhh i see, baik baik ku coba refactor code ku sebentar :smile:

2021-06-21 16:31 UTC, rachadiannovansyah commented
Ada beberapa update mas @yohang88, boleh ditengok :rocket:

2021-06-22 02:45 UTC, yohang88 approved these changes

2021-06-22 02:45 UTC, merged