Applicant check profile feature
jabardigitalservice/pikobar-rapidtest-api pull request #22
Opened 2020-09-02 09:31 UTC by nurisakbar

### Overview
Fitur untuk melakukan cek profile peserta dengan mengirimkan parameter nomor registration_code .

CC : @yohang88 

### Related Task :
https://trello.com/c/Vsa6gdKC/90-nik-hanya-bisa-digunakan-sekali-ketika-registrasi

2020-09-03 00:34 UTC, yohang88 requested changes
Yuhuuu minor revisi aja @nurisakbar 😁 👍 

Btw itu ada pipeline CI/CD Travis yang failed, minta tologn dicek juga yak.

2020-09-03 00:34 UTC, yohang88 commented on app/Http/Controllers/Rdt/ApplicantsCekProfileController.php
> +namespace App\Http\Controllers\Rdt;
Ini sepertinya perlu disamakan dengan namespace Checkin yang kemarin 😁

2020-09-03 00:34 UTC, yohang88 commented on app/Http/Controllers/Rdt/ApplicantsCekProfileController.php
> +class ApplicantsCekProfileController extends Controller
Karena applicant yang dicek hanya 1 dan returnnya pun hanya 1, maka sebaiknya penamaannya cukup `Applicant` saja. Tidak pakai es 😁 

`Cek` juga agar konsisten dengan bahasa inggris, sebaiknya `Check` 😁

2020-09-03 00:34 UTC, yohang88 commented on app/Http/Requests/Rdt/ApplicantsCekProfileRequest.php
> +class ApplicantsCekProfileRequest extends FormRequest
Ini sama dengan controllernya yak 😁 
- Bikin namespace Checkin
- Perbaikan naming class

2020-09-03 00:34 UTC, yohang88 commented on app/Http/Controllers/Rdt/ApplicantsCekProfileController.php
> +        return response()->json($response);
ini bisa dibuat hemat 2 baris dengan:
```
return new ApplicantProfileResource($rdtApplicant);
```

2020-09-03 02:35 UTC, nurisakbar commented on app/Http/Controllers/Rdt/ApplicantsCekProfileController.php
> +        return response()->json($response);
siap, udah saya perbaiki kang, mohon direview kembali

2020-09-03 02:35 UTC, nurisakbar commented on app/Http/Controllers/Rdt/ApplicantsCekProfileController.php
> +namespace App\Http\Controllers\Rdt;
siap

2020-09-03 16:08 UTC, nurisakbar commented
perbaikan sudah selesai kang @yohang88

2020-09-04 01:59 UTC, yohang88 requested changes
Dikit lagi gans, tetap semangat 😁

2020-09-04 01:59 UTC, yohang88 commented on app/Http/Requests/Rdt/ApplicantsCekProfileRequest.php
> +class ApplicantsCekProfileRequest extends FormRequest
Ini belum diperbaiki, masih belum berubah

2020-09-04 01:59 UTC, yohang88 commented on app/Http/Controllers/Checkin/ApplicantCheckProfileController.php
> +        return response()->json(new ApplicantProfileResource($rdtApplicant));
ini tidak perlu pakai `response()->json()`, karena cukup pakai otomatis akan jadi json (asalkan pakai request header Accept: application/json):
```
return new ApplicantProfileResource($rdtApplicant)
```

2020-09-04 02:21 UTC, nurisakbar commented on app/Http/Controllers/Checkin/ApplicantCheckProfileController.php
> +        return response()->json(new ApplicantProfileResource($rdtApplicant));
siap, perbaikan done kang @yohang88

2020-09-04 03:34 UTC, yohang88 commented on app/Http/Requests/Rdt/ApplicantsCekProfileRequest.php
> +class ApplicantsCekProfileRequest extends FormRequest
Ini kan belum diperbaiki, nama class dan namespace belum disesuaikan

2020-09-04 04:26 UTC, nurisakbar commented
perbaikan selesai, cc : @yohang88

2020-09-04 06:14 UTC, yohang88 approved these changes

2020-09-04 06:15 UTC, merged