Pertanyaan tambahan ketika register
jabardigitalservice/pikobar-rapidtest-api pull request #24
Opened 2020-09-03 15:54 UTC by nurisakbar

### Overview
Penambahan informasi kota yang dikunjungi, apakah pernah berinteraksi dengan pasien covid, dan penyakit bawaan.

CC :  @yohang88 

### Related Task :
https://trello.com/c/W5xQWw2y/86-revisi-microsite

2020-09-04 03:33 UTC, yohang88 requested changes
Cekidot 😁

2020-09-04 03:33 UTC, yohang88 commented on app/Http/Requests/Rdt/RdtRegisterRequest.php
> +            'suspect_probable'     => 'required',
Ini perlu penanganan jika API dideploy dulu sebelum frontend/microsite-nya selesai. Karena kalau API-nya required, tapi microsite-nya belum ada formnya, maka akan jadi stopper.

2020-09-04 03:33 UTC, yohang88 commented on app/Entities/RdtApplicant.php
> +        'latitude', 'longitude', 'pikobar_session_id', 'pikobar_user_id','city_visited','congenital_disease','suspect_probable'
Tambahkan spasi antar member array. 

`congenital_disease` itu apa ya?

2020-09-04 03:33 UTC, yohang88 commented on app/Entities/RdtApplicant.php
> +        'latitude', 'longitude', 'pikobar_session_id', 'pikobar_user_id','city_visited','congenital_disease','suspect_probable'
`suspect_probable` ini untuk field pertanyaan yang mana ya? Kalau pertanyaan-nya "pernah berinteraksi", maka naming-nya kurang sesuai.

2020-09-04 03:33 UTC, yohang88 commented on app/Entities/RdtApplicant.php
>          'is_pns'            => 'boolean',
Yang "pernah berinteraksi" itu ga di-cast jadi boolean?

2020-09-04 03:44 UTC, nurisakbar commented on app/Entities/RdtApplicant.php
>          'is_pns'            => 'boolean',
value nya nanti iya, tidak atau tidak tau jadi bukan boolean kang

2020-09-04 03:46 UTC, nurisakbar commented on app/Entities/RdtApplicant.php
> +        'latitude', 'longitude', 'pikobar_session_id', 'pikobar_user_id','city_visited','congenital_disease','suspect_probable'
saya ngikutin breefing dari front end ^_^,  atau cocok nya have_interacted kali ya ?

2020-09-04 03:47 UTC, nurisakbar commented on app/Http/Requests/Rdt/RdtRegisterRequest.php
> +            'suspect_probable'     => 'required',
kemarin ketika tiktok dengan frontend  dia ngasi info parameter yang akan dikirimkan, barusan setelah daily udah saya sampaikan juga agar frontend diberesin dulu baru nanti saya sesuaikan di backend

2020-09-04 06:22 UTC, yohang88 requested changes
Sedikit lagiii 😁

2020-09-04 06:22 UTC, yohang88 commented on app/Http/Requests/Rdt/RdtRegisterRequest.php
> +            'suspect_probable'     => 'required',
@nurisakbar kita selalu deploy API first yak, tidak terlalu depend dengan frontend. Dan sebaiknya kita mendesain agar API bisa menangani kondisi tersebut. Jika frontend belum update, maka API harus bisa jalan. Ini kondisi yang sering kejadian, misal:

Karena suatu hal, mobile app/frontend ada stopper issue, sehingga harus mobile app/frontend di-rollback.

Maka sebaiknya validasi ini ditambahkan jika POST data dari frontend memiliki attribut tersebut. Biasanya kita pakai validator `sometimes`.

2020-09-04 06:22 UTC, yohang88 commented on app/Entities/RdtApplicant.php
> +        'latitude', 'longitude', 'pikobar_session_id', 'pikobar_user_id','city_visited','congenital_disease','suspect_probable'
@nurisakbar oke sepakat.

2020-09-04 06:22 UTC, yohang88 commented on app/Entities/RdtApplicant.php
>          'is_pns'            => 'boolean',
Nah kalau ada 3 value seperti itu, berarti jangan pakai integer tipe datanya. Daripada pakai integer, lebih baik pakai enum value. Contoh ada di enum SymptomsInteraction.

Kenapa bukan integer? Wah ini perlu sesi diskusi khusus nampaknya 😀

2020-09-04 06:36 UTC, nurisakbar commented on app/Entities/RdtApplicant.php
>          'is_pns'            => 'boolean',
karna value yang dikirim 1 untuk ya, 2 untuk tidak dan 3 untuk tidak tau jadi saya fikir pakai integer

2020-09-04 08:17 UTC, yohang88 commented on app/Entities/RdtApplicant.php
>          'is_pns'            => 'boolean',
Nah maka sebaiknya data apa yang dikirim, itu didefinisikan bareng. Di frontend pun sama, kita selalu mengurangi penggunaan integer, lebih baik pakai enum 😁

2020-09-04 10:37 UTC, nurisakbar commented
cc kang @yohang88

2020-09-04 14:27 UTC, yohang88 requested changes
Dikit lagi @nurisakbar 😁

2020-09-04 14:27 UTC, yohang88 commented on app/Http/Requests/Rdt/RdtRegisterRequest.php
> +            'have_interacted'      => 'sometimes',
Coba pelajari dulu https://laravel.com/docs/7.x/validation#conditionally-adding-rules bagian sub *Validating When Present*

2020-09-04 14:27 UTC, yohang88 commented on composer.json
> +        "doctrine/dbal": "^2.10.3",
Ini package untuk modify tipe data, kolom apakah yang mau diganti tipe datanya ya?

2020-09-04 14:29 UTC, yohang88 requested changes
Tambahan dikit

2020-09-04 14:29 UTC, yohang88 commented on database/migrations/2020_09_03_085437_add_column_city_visited_congenital_disease.php
> +            $table->tinyInteger('have_interacted')->nullable();
Ini masih pakai integer?

2020-09-05 02:34 UTC, nurisakbar commented on composer.json
> +        "doctrine/dbal": "^2.10.3",
perubahan terakhir langsung drop column yang suspect_probable dan ganti pakai have_interacted, jadi gak pakai flow perubahan nama column.

package ini juga akan dihapus karna gak jadi dipakai

2020-09-05 02:37 UTC, nurisakbar commented on database/migrations/2020_09_03_085437_add_column_city_visited_congenital_disease.php
> +            $table->tinyInteger('have_interacted')->nullable();
kalau ngikutin SymptomsInteraction type data nya tinyInteger kang, lalu baru di set enumclass nya di model,
apakah saya salah tangkap maksudnya ?

2020-09-05 02:42 UTC, nurisakbar commented on app/Http/Requests/Rdt/RdtRegisterRequest.php
> +            'have_interacted'      => 'sometimes',
berarti tambahin sometime|required ya kang

2020-09-05 08:19 UTC, yohang88 requested changes
Dikit lagiii

2020-09-05 08:19 UTC, yohang88 commented on app/Http/Requests/Rdt/RdtRegisterRequest.php
> +            'have_interacted'      => 'sometimes',
@nurisakbar iyes. Jadi harapannya, jika microsite-nya belum selesai, production tetap bisa jalan karena microsite yang existing (yang lama) belum ada field isiannya. Kalau hanya dibuat `required` di API, nanti jadi stopper.

2020-09-05 08:19 UTC, yohang88 commented on composer.json
> +        "doctrine/dbal": "^2.10.3",
kalau ga dipakai dihapus aja (jangan lupa composer update lagi), biar packages-Dockerfilenya ga tambah besar ukurannya 😁

2020-09-05 08:19 UTC, yohang88 commented on database/migrations/2020_09_03_085437_add_column_city_visited_congenital_disease.php
> +            $table->tinyInteger('have_interacted')->nullable();
@nurisakbar Betul. Nah, kolom dan enum `SymptomsInteraction` itu technical debt dari sistem sebelumnya (yang kita kerjakan ini adalah rewrite dari aplikasi .Net sebelumnya 😁) Kesalahan saya adalah membuat tidak konsisten: Di database pakai integer, tapi di aplikasi pakai Enum.

Sebaiknya ke depan kita konsisten pakai enum, misal: `YES`, `NO`, `UNKNOWN` atau bisa dilihat di `PersonCaseStatusEnum`. Dan itu dipakai di frontend, database (varchar), dan aplikasi. 😁

2020-09-05 08:19 UTC, yohang88 commented on app/Http/Requests/Rdt/RdtRegisterRequest.php
> +            'have_interacted'      => 'sometimes',
Iyes. Sehingga backend tetap bisa menghandle kondisi jika frontend (microsite) belum ada field `have_interacted`, `congenital_disease`, dsb. Tapi kalau frontend (microsite) udah ada fieldnya, akan jadi required (perlu di-highlight bagian `if present`)

2020-09-07 02:52 UTC, nurisakbar commented
perubahan udah dipush, cc : @yohang88

2020-09-07 08:30 UTC, yohang88 requested changes
Penerapan enum belum sesuai, coba pelajari existing code 😁 

Itu composer.lock saya lihat ikut dicommit. Kalau tidak ada perubahan, bisa di-revert saja filenya (discard-changes, dibalikin ke kondisi awal sesuai dari branch develop/master).

2020-09-07 08:30 UTC, yohang88 commented on database/migrations/2020_09_03_085437_add_column_city_visited_congenital_disease.php
> +            $table->enum('have_interacted', ['YA','TIDAK','TIDAK TAHU'])->nullable();
Ini masih belum sesuai sih, sudah coba pelajari implementasi class enum object di `App\Enums` ?

2020-09-08 07:23 UTC, nurisakbar commented
cc kang @yohang88

2020-09-08 09:12 UTC, yohang88 requested changes
Mantap dikit lagi 😂 @nurisakbar

2020-09-08 09:12 UTC, yohang88 commented on app/Enums/HaveInteractedEnum.php
> + * @method static self YA()
minor, coba pakai bahasa inggris yaaak 😁

2020-09-08 13:11 UTC, nurisakbar commented on app/Enums/HaveInteractedEnum.php
> + * @method static self YA()
siap udah diperbaiki kang @yohang88

2020-09-09 03:22 UTC, yohang88 approved these changes
Mantap, makasih banyak @nurisakbar 👍 😁

2020-09-09 03:24 UTC, merged