Export rdt invitations format f1
jabardigitalservice/pikobar-rapidtest-api pull request #29
Opened 2020-09-10 07:30 UTC by nurisakbar

### Overview
Export data peserta dengan menggunakan format F1.

CC : @yohang88 

### Related Task
https://trello.com/c/i4taU4Ak/87-revisi-export

2020-09-10 09:17 UTC, yohang88 requested changes
Yuhuuuu semangat @nurisakbar 💪 😁

2020-09-10 09:17 UTC, yohang88 commented on composer.json
> +        "box/spout": "2.7.0",
Ini kenapa diganti ya? Yang sebelumnya versi berapa ya? Takutnya nyenggol codingan import/export yang lain. Karena pakai fast-excel, harusnya yang box/spout ga diganti kan?

2020-09-10 09:17 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +                    'JENIS_KELAMIN' => $row->gender == 1 ? 'Laki-Laki' : 'Perempuan',
Manfaatkan Gender Enum-nya aja, daripada angka `1` ini bikin bertanya-tanya apa artinya.

2020-09-10 09:17 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +                    'TANGGAL_ACARA' => $row->start_at,
Seingat saya database-nya dalam timezone UTC (GMT). Sehingga saat di-export/ditampilkan seharusnya dikonversi ke timezone WIB/Asia Jakarta. Berlaku juga untuk field yang pakai tipe data timestamp/datetime.

2020-09-10 09:17 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +        $fileName = str_replace(" ", "-", $rdtEvent->event_name) . '.xlsx';
Fungsi replace menjadi `-` (safe filename) itu bisa pakai `Slug`-nya Laravel, dan lebih bisa menghandle banyak cases (misal karakter selain alfabet-numerik).

2020-09-10 09:17 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +        DB::statement(DB::raw('set @number=0'));
Untuk bikin penomoran, harus pakai di SQL query? Kenapa tidak pakai semacam `$n++` di dalam iterasi setiap row?

2020-09-10 09:17 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +class RdtInvitationExportExcelF1Controller extends Controller
Agar konsisten dengan nama controller exporter participant lainnya, sebaiknya pakai naming participant list juga.

2020-09-10 09:17 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +        File::delete(public_path($this->fileName));
Ini kenapa perlu di-delete? Apa yang terjadi jika tidak didelete?

2020-09-10 09:17 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +        $file = public_path($fileName);
Filenya harus disimpan di folder public? Ga bisa langsung stream output ke client/browser?

2020-09-10 09:32 UTC, nurisakbar commented on composer.json
> +        "box/spout": "2.7.0",
sebelumnya belum pernah ada yang pakai package ini, ini diganti karna ternyata versi tersebut dan cocok dengan requretment laravel nya. jadi downgrade

2020-09-10 09:33 UTC, nurisakbar commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +        DB::statement(DB::raw('set @number=0'));
ini gak di foreach di layer controller data nya, jadi di handle di sql query

2020-09-10 09:34 UTC, nurisakbar commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +        File::delete(public_path($this->fileName));
hasil generate di simpan di folder public, atau apakah hasil export dibiarkan saja ? ( nanti dipindahkan ke storage )

2020-09-10 09:35 UTC, nurisakbar commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +        $file = public_path($fileName);
iya, by default dia nge generate ke folder public, belum ada opsi agar langsung download

2020-09-10 09:38 UTC, nurisakbar commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +class RdtInvitationExportExcelF1Controller extends Controller
siap

2020-09-10 11:59 UTC, nurisakbar commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +                    'JENIS_KELAMIN' => $row->gender == 1 ? 'Laki-Laki' : 'Perempuan',
yang ini minta nya Laki Laki Dan Perempuan, Kalau Yang Di Enum Pakai MALE Dan FEMALE

2020-09-10 13:08 UTC, yohang88 commented on composer.json
> +        "box/spout": "2.7.0",
Package `box/spout` sudah dipakai, salah satunya di `RdtEventParticipantImportResultController`. Sehingga kalau didowngrade, perlu dilakukan regresi test apakah fungsionalnya normal atau tidak.

2020-09-10 13:13 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +                    'JENIS_KELAMIN' => $row->gender == 1 ? 'Laki-Laki' : 'Perempuan',
Fokusnya pada komparasi value `1`.  Untuk tahu apa angka 1 ini darimana? Ada value apa saja yang tersedia selain angka 1? Maka gunakan Enum. Mana yang lebih mudah dibaca:

```
$row->gender == 1
```
atau,
```
$row->gender->isEqual(Gender::MALE) 
```

Catatan nomor 2, apa outputnya jika value di database `NULL`?

2020-09-10 13:20 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +                    'JENIS_KELAMIN' => $row->gender == 1 ? 'Laki-Laki' : 'Perempuan',
Btw issue lain, ini kayaknya ada anomali kesenggol, seharusnya value-nya itu `M` atau `F`, bukan `1` atau `0`. Karena di database production seperti itu. Untuk ini saya bantu cek.

2020-09-10 13:20 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +        $file = public_path($fileName);
Saya lihat sekilas di dokumentasinya ada contoh bagian `Download (from a controller method)`, itu bisa dipakai ga ya?

2020-09-10 13:27 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +        File::delete(public_path($this->fileName));
Paling aman tetap gunakan storage yang private sih. Atau disimpan di AWS S3 storage 😁

2020-09-10 13:27 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +        DB::statement(DB::raw('set @number=0'));
woke sipp

2020-09-11 02:18 UTC, nurisakbar commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +        $file = public_path($fileName);
ouh bisa ternyata, udah saya implementasikan juga untuk hal ini, nuhun

2020-09-11 02:19 UTC, nurisakbar commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +                    'JENIS_KELAMIN' => $row->gender == 1 ? 'Laki-Laki' : 'Perempuan',
ketika seeding data gender nya ke isi 0 dan 1

2020-09-11 02:24 UTC, nurisakbar commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +                    'JENIS_KELAMIN' => $row->gender == 1 ? 'Laki-Laki' : 'Perempuan',
$row->gender->isEqual(Gender::MALE) 

untuk sekarang kan pakai query builder bukan eloquen nya kang @yohang88

2020-09-11 06:52 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +                    'JENIS_KELAMIN' => $row->gender == 1 ? 'Laki-Laki' : 'Perempuan',
waduh, untuk Seeding minta tolong coba dibantu cek, seharusnya valuenya `M` atau `F` sih, sesuai file enumnya Gender 😂 

Nah kalau ga pakai eloquent, berarti bisa pakai komparasi gini ga ya?
```
if ($row->gender === Gender::MALE()->getValue()) // atau getName()
```

2020-09-11 07:14 UTC, nurisakbar reviewed
yang ini kang @yohang88

2020-09-11 07:40 UTC, nurisakbar commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +                    'JENIS_KELAMIN' => $row->gender == 1 ? 'Laki-Laki' : 'Perempuan',
jadinya gini : Gender::MALE()->getValue()===$row->gender?'Laki Laki':'Perempuan',

udah saya implementasikan , boleh di review lagi kang @yohang88

2020-09-11 11:51 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +                    'JENIS_KELAMIN' => $row->gender == 1 ? 'Laki-Laki' : 'Perempuan',
@nurisakbar woke sip

Sundul ini: Catatan nomor 2, apa outputnya jika value di database NULL atau value-lain, misal ga sengaja terisi karakter lain?

2020-09-11 15:35 UTC, nurisakbar commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +                    'JENIS_KELAMIN' => $row->gender == 1 ? 'Laki-Laki' : 'Perempuan',
@yohang88  :  testing value nya di isi 1, null dan string lain yang muncul adalah perempuan

2020-09-11 16:57 UTC, yohang88 commented on app/Http/Requests/Rdt/RdtRegisterRequest.php
> +            'have_interacted'      => 'required',
ini kenapa dibalikin jadi `required` lagi?

2020-09-12 02:21 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +                    'JENIS_KELAMIN' => $row->gender == 1 ? 'Laki-Laki' : 'Perempuan',
@nurisakbar nah apakah itu expected result? kalau ada `NULL`, dsb akan muncul sebagai perempuan? Seharusnya enggak kan ya? 😁

2020-09-12 12:39 UTC, nurisakbar commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +                    'JENIS_KELAMIN' => $row->gender == 1 ? 'Laki-Laki' : 'Perempuan',
@yohang88  : yes bener, selain itu dijadikan kosong aja ya

2020-09-12 12:49 UTC, nurisakbar commented on app/Http/Requests/Rdt/RdtRegisterRequest.php
> +            'have_interacted'      => 'required',
siap udah dikembalikan seperti semula

2020-09-12 16:38 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +                    'JENIS_KELAMIN' => $row->gender == 1 ? 'Laki-Laki' : 'Perempuan',
@nurisakbar Sepakat. Ini sering kejadian di kita pakai `if-else`, pas datanya banyak yang `null` (karena misal ga mandatory), pas digenerate/export jadinya banyak Laki-Laki atau Perempuan 😁

2020-09-12 16:39 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +                    'TANGGAL_ACARA' => $row->start_at,
Up ini yak, kalau ada kendala/mungkin saya kurang jelas, siaap untuk diskusi 😁

2020-09-12 16:39 UTC, yohang88 commented on composer.json
> +        "box/spout": "2.7.0",
Up sundul ini juga :grin

2020-09-13 04:42 UTC, nurisakbar commented on app/Http/Controllers/Rdt/RdtInvitationExportExcelF1Controller.php
> +                    'TANGGAL_ACARA' => $row->start_at,
udah di perbaiki kang, sekarang jadi gini : 'TANGGAL_ACARA' => Carbon::parse($row->start_at)->format('Y-m-d'),
                    'JAM_ACARA' => Carbon::parse($row->start_at)->format('H:i:s') . ' - ' . Carbon::parse($row->end_at)->format('H:i:s'),

2020-09-13 04:53 UTC, nurisakbar commented on composer.json
> +        "box/spout": "2.7.0",
@yohang88  : pas export muncul error kayak gini : 

message: Cannot connect to service. Message: cURL error 7: Failed to connect to localhost port 5000: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

gambar : https://ibb.co/0VS9H3V

2020-09-13 06:26 UTC, yohang88 commented on composer.json
> +        "box/spout": "2.7.0",
@nurisakbar oh beda issue kalau ini, localhost:5000 itu kan karena fitur export yang lama dilempar ke webservice python terpisah. Jadi memang harusnya running laravel dan pythonnya kalau mau exportnya jalan.

Tapi untuk fitur import2 yang pakai box/spout, harusnya normal.

2020-09-13 06:28 UTC, nurisakbar commented on composer.json
> +        "box/spout": "2.7.0",
jadi apa bisa kita test di staging aja ?

2020-09-13 06:35 UTC, yohang88 commented on composer.json
> +        "box/spout": "2.7.0",
@nurisakbar balikin dulu box/spoutnya ke versi yang lama :))) Karena pasti akan kita deploy ke production juga (perbaikan yang city_visited)

2020-09-13 06:39 UTC, nurisakbar commented on composer.json
> +        "box/spout": "2.7.0",
@yohang88  :  kalau dibalikin ke spout versi awal kayaknya yang akan terjadi adalah  package rap2hpoutre /
fast-excel gak bisa di install dan akan terjadi gagal deploy, mohon koreksi kalau asumsi tersebut salah

2020-09-13 06:41 UTC, yohang88 commented on composer.json
> +        "box/spout": "2.7.0",
@nurisakbar wadidaw. Berarti untuk export/import ini kita lanjutkan dalami dulu aja besok, karena perlu dicek lagi impact ke fitur2 import-import yang pakai `box/spout` (apalagi ini yang ngerjain relawan). Jadi lebih baik sekarang untuk fix `city_visited`, tolong bikin branch baru + pull request baru aja ya, biar tidak menganggu yang ini.

2020-09-14 03:41 UTC, nurisakbar commented on composer.json
> +        "box/spout": "2.7.0",
jadi yang ini jadi gimana kang @yohang88  ?

2020-09-14 07:53 UTC, nurisakbar commented
sekarang untuk export sudah pakai box/spout, hasil exportnya jadi 11 detik, ada penambahan 3 field baru juga dari kemarin.
[2020-09-14 07:45:56] local.INFO: start  
[2020-09-14 07:46:05] local.INFO: end  

cc : @yohang88

2020-09-14 08:38 UTC, yohang88 approved these changes
Woke siip mantaaap @nurisakbar setelah perjuangan panjang nan melelahkan 👍 😂

2020-09-14 08:41 UTC, merged