handling filter except published and draft
jabardigitalservice/pikobar-rapidtest-api pull request #35
Opened 2020-09-15 07:29 UTC by nurisakbar

### Overview
Sebelumnya jika dipilih filter semua maka sistem akan memunculkan list event yang status nya draft, karna by default ketika halaman kegiatan di akses tidak mengirimkan parameter status. 

PR ini menghadle masalah ini, jadi filter status hanya akan di eksekusi kalau parameter status berisi value draft atau publised, selain itu akan mereturn semua event.

CC : @yohang88 

### Related Task : 
https://trello.com/c/v7WBtdde/101-kegiatan-bug-filter-status

2020-09-15 10:13 UTC, yohang88 requested changes
Cek cek dulu.

2020-09-15 10:13 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtEventController.php
> +        $status    = $request->input('status', 'semua');
Attribut yang dikirim dari frontend apa ya? "semua" ?

2020-09-15 10:13 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtEventController.php
> +        if ($status == 'draft' || $status == 'published') {
- Hindari `if` di dalam `if`
- Periksa konsistensinya, kenapa ada yang pakai `==` dan ada yang pakai `===`

2020-09-15 11:39 UTC, nurisakbar commented on app/Http/Controllers/Rdt/RdtEventController.php
> +        $status    = $request->input('status', 'semua');
pertama kali membuka halaman kegiatan, filter status yang terpilih adalah semua tapi filter ini tidak memiliki value.
jadi kalau misalnya default dari request status dibackend adalah draft maka ketika membuka halaman kegiatan akan menampilkan kegiatan dengan status draft, dan ketika melakukan filter status dengan option semua juga akan muncul data dengan status draft.

2020-09-15 11:39 UTC, nurisakbar commented on app/Http/Controllers/Rdt/RdtEventController.php
> +        if ($status == 'draft' || $status == 'published') {
siap

2020-09-15 11:50 UTC, nurisakbar commented on app/Http/Controllers/Rdt/RdtEventController.php
> +        $status    = $request->input('status', 'semua');
tadi udah request ke frontend untuk filter status dropdown dengan label semua agar diberi value semua

2020-09-16 01:52 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtEventController.php
> +        $status    = $request->input('status', 'semua');
woke sip

2020-09-16 01:52 UTC, yohang88 approved these changes

2020-09-16 01:53 UTC, merged