Add colum Tempat Lahir
jabardigitalservice/pikobar-rapidtest-api pull request #39
Opened 2020-09-17 09:09 UTC by nurisakbar

### Overview
Menambahkan Field birth_place untuk menyimpan informasi tempat lahir.

CC : @yohang88

2020-09-17 09:20 UTC, yohang88 requested changes
Minor revisi saja

2020-09-17 09:20 UTC, yohang88 commented on database/migrations/2020_09_17_090249_add_column_birth_place.php
> +            $table->string('birth_place', 60)->nullable();
Karena dibatasi 60 karakter, sebaiknya ditambahkan validasi juga saat request disimpan.

Gunakan method after() untuk menaruh kolom baru ini setelah kolom tanggal lahir.

2020-09-17 09:21 UTC, nurisakbar commented on database/migrations/2020_09_17_090249_add_column_birth_place.php
> +            $table->string('birth_place', 60)->nullable();
siap

2020-09-17 09:29 UTC, nurisakbar commented on database/migrations/2020_09_17_090249_add_column_birth_place.php
> +            $table->string('birth_place', 60)->nullable();
done @yohang88

2020-09-18 04:30 UTC, yohang88 approved these changes

2020-09-18 04:31 UTC, merged