Add fasyankes data source
jabardigitalservice/pikobar-rapidtest-api pull request #45
Opened 2020-09-23 04:54 UTC by nurisakbar

### Overview
penambahan data fasyankes yang bersumber dari file array.

Cc : @yohang88

2020-09-23 06:12 UTC, yohang88 requested changes
minor saja

2020-09-23 06:12 UTC, yohang88 commented on app/Http/Controllers/Master/FasyankesListController.php
> +        return response()->json($fasyankes->items(), 200);
Tidak perlu ada status code 200, karena by default sudah `OK`.

2020-09-23 06:12 UTC, yohang88 commented on app/Entities/Fasyankes.php
> +    public function items(): array
- Karena tipe `dinkes` itu seharusnya ga ada, sebaiknya dihapus saja semua recrod yang tipe `dinkes`.
- Attribute `kota_id` juga ga relevan di tes masif, sebaiknya dihapus.
- Attribut `nama`, `tipe` seharusnya konsisten bahasa inggris saja.

2020-09-23 06:34 UTC, nurisakbar commented on app/Entities/Fasyankes.php
> +    public function items(): array
@yohang88  :  jadi untuk data dengan type dinkes dihapus semua ?

o iya ini dari seeder project labkes, ketika cek di staging ternyata mereka punya 215 data untuk fasyankes

2020-09-23 09:47 UTC, yohang88 requested changes

2020-09-23 09:47 UTC, yohang88 commented on app/Entities/Fasyankes.php
> +    protected $fillable = [
attribute di `$fillable` ini tidak konsisten dengan penulisan di migration, resource.

2020-09-23 09:47 UTC, yohang88 commented on database/seeds/FasyankesSeeder.php
> +                "type"=> "dinkes",
Dinkes itu seharusnya bukan Faskes. Karena namanya pun nama Kota/Kab.

2020-09-23 10:13 UTC, nurisakbar commented on database/seeds/FasyankesSeeder.php
> +                "type"=> "dinkes",
ini sample data dari production labkes kang @yohang88 
https://ibb.co/VLCT8QX

2020-09-24 06:02 UTC, yohang88 requested changes
Tolong diperbaiki dulu

2020-09-24 06:02 UTC, yohang88 commented on database/seeds/FasyankesSeeder.php
> +        foreach ($this->items() as $item) {
Ini kenapa harus dibuat seperti ini ya?

2020-09-24 06:02 UTC, yohang88 commented on app/Http/Controllers/Master/FasyankesListController.php
> +            $fasyankes = Fasyankes::where('name', 'like', "%" . $request->name . "%")->get();
Perlu konsistensi penulisan single quote vs double quote

2020-09-24 06:04 UTC, nurisakbar commented on database/seeds/FasyankesSeeder.php
> +        foreach ($this->items() as $item) {
copy dari project labkes sih sebenarnya, karna dari dulu udah jalan jadi gak di ubah lagi ^_^

2020-09-24 06:23 UTC, yohang88 commented on database/seeds/FasyankesSeeder.php
> +                "name"=> "RSUP Dr. Hasan Sadikin",
Tambahkan spasi di antara arrow key dan value array

2020-09-24 06:43 UTC, yohang88 commented on app/Http/Controllers/Master/FasyankesListController.php
> +        if ($search) {
ini sebaiknya pakai `has($key)`, jadi saat membaca, orang langsung paham

2020-09-24 06:44 UTC, yohang88 commented on app/Http/Controllers/Master/FasyankesListController.php
> +        } else {
Ini sepertinya bisa dibuat tanpa pakai `else`.

2020-09-24 06:44 UTC, yohang88 requested changes
Cek dikit lagi

2020-09-24 08:12 UTC, yohang88 approved these changes
oke

2020-09-24 08:12 UTC, merged