Update lab result type
jabardigitalservice/pikobar-rapidtest-api pull request #57
Opened 2020-10-14 23:54 UTC by nurisakbar

### Overview
Ednpoint yang akan digunakan untuk melakukan perubahan hasil pemeriksaan.

### Related Task :
https://trello.com/c/DBpbqTrs/125-admin-bisa-mengubah-hasil-tes-peserta-dari-dalam-dashboard

cc : @yohang88

2020-10-15 06:52 UTC, yohang88 requested changes
@nurisakbar minor aja yes.

2020-10-15 06:52 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtInvitationLabResultUpdateController.php
> +        return response()->json(['message' => 'Hasil Pemeriksaan Kode Sampel ' . $rdtInvitation->lab_code_sample . ' Berhasil Di Ubah Menjadi ' . $request->lab_result_type]);
Nampaknya dari backend tidak perlu response string yang lengkap, cukup `OK` kalau berhasil, misal. Agar penanganan string/kalimatnya ditangani di frontend saja 😁

2020-10-16 01:48 UTC, nurisakbar commented on app/Http/Controllers/Rdt/RdtInvitationLabResultUpdateController.php
> +        return response()->json(['message' => 'Hasil Pemeriksaan Kode Sampel ' . $rdtInvitation->lab_code_sample . ' Berhasil Di Ubah Menjadi ' . $request->lab_result_type]);
siap, udah saya update message nya menjadi OK
cc : @yohang88

2020-10-16 02:44 UTC, yohang88 approved these changes

2020-10-16 02:44 UTC, merged