add category kegiatan
jabardigitalservice/pikobar-rapidtest-api pull request #58
Opened 2020-10-20 12:36 UTC by nurisakbar

### Overview
Penambahan Kategori kegiatan ketika export F1, format kategorinya nama event tanggal

### Related Task :
https://trello.com/c/pwRLGogz/132-export-f1-data-di-kategori-diganti-dengan-judul-kegiatan-ddmmyyyy

CC : @yohang88

2020-10-21 11:14 UTC, yohang88 requested changes
Ceki ceki yes

2020-10-21 11:14 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtEventParticipantListExportF1Controller.php
> +                        $rdtEvent->event_name . ' ' . Carbon::parse($row->attended_at)->format('dmY'),
@nurisakbar `attended_at` ini kalau isinya NULL gimana?

2020-10-25 22:49 UTC, nurisakbar commented on app/Http/Controllers/Rdt/RdtEventParticipantListExportF1Controller.php
> +                        $rdtEvent->event_name . ' ' . Carbon::parse($row->attended_at)->format('dmY'),
@yohang88 seharusnya yang null gak ikut ke export data nya, sekarang udah diperbaiki dengan penambahkan filter yang attended_at tidak null

2020-10-27 02:43 UTC, yohang88 approved these changes

2020-10-27 02:43 UTC, merged