penyesuaikan person status dengan format dari labkes
jabardigitalservice/pikobar-rapidtest-api pull request #65
Opened 2020-11-04 07:41 UTC by nurisakbar

### Overview
Penyesuaian value dari field person_status, di sesuaikan dengan format yang dipakai oleh labkes.

cc : @yohang88

2020-11-04 07:48 UTC, yohang88 approved these changes

2020-11-04 07:56 UTC, yohang88 requested changes
Conflict tolong diperbaiki dulu

2020-11-04 10:48 UTC, nurisakbar commented
ready review kang @yohang88

2020-11-05 04:32 UTC, yohang88 approved these changes

2020-11-05 04:32 UTC, yohang88 requested changes

2020-11-05 04:32 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtEventParticipantListExportF1Controller.php
> +use DateTime;
ini untuk apa ya?

2020-11-05 04:35 UTC, nurisakbar commented on app/Http/Controllers/Rdt/RdtEventParticipantListExportF1Controller.php
> +use DateTime;
@yohang88  :  di line 141 pakai DateTime dan DateTimeZone

2020-11-05 06:12 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtEventParticipantListExportF1Controller.php
> +use DateTime;
@nurisakbar Seingat saya ini pernah bisa pakai bawaan Carbon dari object datetime di Laravelnya. Sekaligus sudah ada config timezone untuk frontend/export. Coba search di codebase `/app` yang pakai method Carbon `setTimezone()`.

2020-11-05 08:55 UTC, nurisakbar commented on app/Http/Controllers/Rdt/RdtEventParticipantListExportF1Controller.php
> +use DateTime;
udah coba pakai itu kemarin tapi error pas write ke spoutnya, jadi pakai cara yang sekarang

2020-11-05 09:19 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtEventParticipantListExportF1Controller.php
> +use DateTime;
Errornya apa ya @nurisakbar ?

2020-11-06 09:40 UTC, nurisakbar commented on app/Http/Controllers/Rdt/RdtEventParticipantListExportF1Controller.php
> +use DateTime;
@yohang88 : udah solved, kemarin kurang fokus aja kayaknya

2020-11-06 10:43 UTC, nurisakbar commented on app/Http/Controllers/Rdt/RdtEventParticipantListExportF1Controller.php
> +use DateTime;
udah berhasil implementasi carbon, cc : kang @yohang88

2020-11-08 02:01 UTC, nurisakbar commented
implementasi timezone dari config done, cc : @yohang88

2020-11-08 17:22 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtEventParticipantListExportF1Controller.php
> +                        Carbon::createFromFormat('Y-m-d H:i:s', $row->attended_at)->setTimezone(config('app.timezone_frontend'))->toDateTimeString(),
Sebaiknya dipisahkan/didefinisikan di variable terpisah dulu, tidak langsung ditulis di sini karena code jadi akan terlalu lebar (coba periksa dengan php-cs).

2020-11-09 02:51 UTC, nurisakbar commented
kang @yohang88 , ini CI nya pending terus udah sekitar 1/2 jam lebih, kayaknya ada masalah

2020-11-09 03:08 UTC, yohang88 approved these changes

2020-11-09 03:08 UTC, merged