Integrasi dengan labkes bulk insert
jabardigitalservice/pikobar-rapidtest-api pull request #72
Opened 2020-11-09 10:49 UTC by nurisakbar

### Overview
Integrasi dengan labkes dengan pengiriman array, hasil test 2000 row menunjukan :
[2020-11-09 10:23:35] local.INFO: start : 2020-11-09 10:23:35  
[2020-11-09 10:24:10] local.INFO: end : 2020-11-09 10:24:10  

### Related Task :
https://trello.com/c/EVttHkAw/131-kegiatan-admin-bisa-mengirim-data-peserta-yang-hadir-di-kegiatan-ke-manajemen-labkesda

CC : @yohang88

2020-11-11 00:37 UTC, yohang88 requested changes
Minta tolong diperbaiki sedikit ya.

2020-11-11 00:37 UTC, yohang88 commented on app/Http/Controllers/SinkronisasiController.php
> +        $response = Http::post($labkesUrl, ['data' => $payload]);
Sebaiknya ditambahkan handling jika server aplikasi manlab error/gagal/tidak available.

2020-11-11 00:37 UTC, yohang88 commented on database/migrations/2020_11_05_072057_add_status_sinkron_to_rdt_invitations.php
> +            $table->datetime('synchronization_at')->after('notified_result_at')->nullable();
Coba berikan argumen/alasan kenapa menggunakan `datetime` dan bukan `timestamp`

2020-11-11 00:37 UTC, yohang88 commented on routes/api.php
> +Route::post('sinkron/{rdtEvent}', 'SinkronisasiController');
beri nama path sesuai dengan fungsinya (sesuai nama controller juga)

2020-11-11 00:37 UTC, yohang88 commented on app/Http/Controllers/SinkronisasiController.php
> +}
Metheod ini terlalu banyak baris, maksimal 25 baris.

2020-11-11 00:37 UTC, yohang88 commented on app/Http/Controllers/SinkronisasiController.php
> +                'jenis_kelamin'         =>  $row->gender == 'M' ? 'L' : 'P',
di atas sudah ada kondisional `$gender`, ini kenapa bikin lagi?

2020-11-11 00:37 UTC, yohang88 commented on app/Http/Controllers/SinkronisasiController.php
> +                'kota_id'               =>  str_replace('.', '', $row->city_code),
Coba cek lagi perbedaan kodefikasi BPS dan Kemendagri. Karena memang ada kode yang berbeda, tidak sekedar berbeda ada `titik`nya.

2020-11-11 00:37 UTC, yohang88 commented on app/Http/Controllers/SinkronisasiController.php
> +                'hasil_rdt'             =>  $row->lab_result_type,
Ini `hasil_rdt` atribut apa ya? Karena kan hasil test itu harusnya di manlab? Kalau udah ada hasilnya, kenapa harus dilempar ke manlab 🤔

2020-11-11 06:32 UTC, nurisakbar commented on app/Http/Controllers/SinkronisasiController.php
> +                'kota_id'               =>  str_replace('.', '', $row->city_code),
iya benar, kemarin sempat ketemu juga case ini untuk desa jabong seperti yang saya sampaikan di group.

2020-11-12 07:52 UTC, nurisakbar commented on app/Http/Controllers/SinkronisasiController.php
> +                'hasil_rdt'             =>  $row->lab_result_type,
ini ngikutin dari format yang diminta labkes waktu import

2020-11-13 02:28 UTC, yohang88 commented on app/Http/Controllers/SinkronisasiController.php
> +                'hasil_rdt'             =>  $row->lab_result_type,
Lho ini proses bisnisnya gimana ya? kan yang melakukan test dan hasil test itu di aplikasi manlab. Kenapa malah ngambil data dari pendaftaran tes masif?

2020-11-16 06:52 UTC, nurisakbar commented
ready review lagi kang @yohang88

2020-11-19 02:01 UTC, yohang88 requested changes
Cek cek sedikit lagi bagian diskusi yang belum solve yak @nurisakbar 😁

2020-11-19 02:01 UTC, yohang88 commented on app/Http/Controllers/SyncToLabkesController.php
> +            return response()->json(['message' => __('response.sync_failed') ], 404);
Sebaiknya error code return-nya tidak selalu harus 404 (karena bisa kode HTTP error yang lain).

2020-11-24 03:38 UTC, yohang88 requested changes
@nurisakbar Minta tolong dicek lagi.

Itu kenapa file `composer.lock` ada commit ya? Saya lihat ga ada perubahan di file `composer.json` yang baru.  Lalu itu file `storage/.DS_Store` juga ikut terbawa commit, tolong dihapus dulu.

2020-11-24 03:38 UTC, yohang88 commented on app/Http/Controllers/SyncToLabkesController.php
> +        $responseStatusCode = $request->getStatusCode();
`Http client` ini jika response dari server error, dia throw exception atau enggak ya?

2020-11-24 03:38 UTC, yohang88 commented on app/Http/Controllers/SyncToLabkesController.php
> +        if ($responseStatusCode == '403') {
HTTP Status Code itu bisa pakai constant dari `Illuminate\Http\Response` dan `Symfony\Component\HttpFoundation\Response`. Dan sebaiknya pakai komparasi yang strict pada tipe datanya. Integer, bukan string.

2020-11-24 03:38 UTC, yohang88 commented on app/Http/Controllers/SyncToLabkesController.php
> +            $result     = json_decode($request->getBody()->getContents());
Terlalu banyak kompleksitas `IF`

2020-11-24 04:26 UTC, nurisakbar commented on app/Http/Controllers/SyncToLabkesController.php
> +            $result     = json_decode($request->getBody()->getContents());
jadi sebaiiknya ambil kondisi apa aja kang ?

2020-11-24 08:05 UTC, nurisakbar commented
update 24 november 2020, change logs :
- implement exception untuk ketika melakukan request dengan guzzle
- menggunakan comparasi status code integer dari getCodeStatus guzzle
- reverse composer.lock

cc : @yohang88

2020-12-01 06:34 UTC, yohang88 commented on app/Http/Controllers/SyncToLabkesController.php
> +                    DB::table('rdt_invitations')->whereIn('lab_code_sample', array_values($result->result->berhasil))->update(['synchronization_at' => now()]);
Terlalu panjang barisnya.

2020-12-01 06:34 UTC, yohang88 commented on app/Http/Controllers/SyncToLabkesController.php
> +            } else {
Kurangi IF di dalam IF

2020-12-02 03:32 UTC, nurisakbar commented
update 1 Desember 2020 :
- remove .DS_store
- remove composer.lock

ready review, cc : @yohang88

2020-12-02 06:36 UTC, nurisakbar commented
update 02-12-2020 :
- perbaikan script yang terlalu panjang 
- perbaikan format tanggal kehadiran ketika export F1 ( perubahan minor )

cc : @yohang88

2020-12-07 06:46 UTC, yohang88 approved these changes

2020-12-07 06:46 UTC, merged