Bulk checkin
jabardigitalservice/pikobar-rapidtest-api pull request #76
Opened 2020-11-16 10:06 UTC by nurisakbar

### Overview
Bulk checkin adalah proses dimana aplikasi mobile bisa melakukan sinkronisasi data checkin secara simultan.
### 
Related Task :
https://trello.com/c/SWsia5yW/129-petugas-bisa-mengecek-data-peserta-meskipun-tidak-ada-koneksi-internet
cc : @yohang88

2020-11-23 03:48 UTC, yohang88 requested changes
Minta tolong dicek terlebih dulu @nurisakbar

2020-11-23 03:48 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtCheckinBulkController.php
> +            if ($rdtInvitation != null) {
Terlalu banyak menggunakan kondisional, meningkatkan kompleksitas untuk memahami. Sebaiknya di-refactor agar tidak banyak nested if.

Coba pelajari juga apakah mungkin pakai `upsert`, `update or insert` sekaligus.

2020-11-23 03:48 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtCheckinBulkController.php
> +        return response()->json(['succes' => $successSync,'failed' => $failedSync]);
Ini di mobile-app penanganan gagalnya gimana ya?

2020-11-24 06:36 UTC, nurisakbar commented on app/Http/Controllers/Rdt/RdtCheckinBulkController.php
> +        return response()->json(['succes' => $successSync,'failed' => $failedSync]);
di mobile nanti akan membaca kode sampel yang gagal untuk diproses ulang kata randi
https://app.slack.com/client/TDK9XJ5EC/C019WAL89LP/thread/C019WAL89LP-1606118754.005200?cdn_fallback=2

2020-11-25 06:17 UTC, yohang88 approved these changes

2020-11-25 06:17 UTC, merged