add filter registration code and event code on checkin
jabardigitalservice/pikobar-rapidtest-api pull request #83
Opened 2020-11-26 13:58 UTC by nurisakbar

### Overview
Penambahan filter event code ketika melakukan checkin, karna ternyata 1 registration code bisa dipakai di beberapa kali event, sebelumnya hanya filter berdasarkan registration code saja.

cc : @yohang88

2020-11-30 06:33 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtCheckinBulkController.php
> +            $rdtInvitation = RdtInvitation::select('rdt_invitations.id', 'rdt_invitations.attended_at')->join('rdt_events', 'rdt_events.id', 'rdt_invitations.rdt_event_id')
Ini sepertinya terlalu panjang barisnya. Wait ini kenapa CodeClimate-nya ga jalan ya.

2020-11-30 06:40 UTC, yohang88 requested changes
Terlalu panjang dalam 1 baris.

2020-11-30 06:56 UTC, nurisakbar commented
@yohang88 siap, udah di rapikan pada line tersebut biar gak terlalu panjang

2020-12-01 03:38 UTC, yohang88 approved these changes

2020-12-01 03:38 UTC, merged