Add sender wa blast invitation
jabardigitalservice/pikobar-rapidtest-api pull request #85
Opened 2020-11-30 03:47 UTC by nurisakbar

### Overview
Menambahkan pencatatan user yang melakukan blast notifikasi.

cc : @yohang88

2020-11-30 04:19 UTC, yohang88 requested changes
Cek dikit lagi.

2020-11-30 04:19 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtEventNotifyTestResultController.php
> +        $invitation->notified_result_by = Auth::user()->name;
Sebaiknya pakai user ID, karena nama bisa berubah.

2020-11-30 04:19 UTC, yohang88 commented on database/migrations/2020_11_30_033715_add_sender_notif_to_table_invitation.php
> +            $table->string('notified_result_by', 50)->after('notified_result_at')->nullable();
Pastikan ditambahkan index untuk kolom-kolom yang akan dipakai untuk query.

2020-11-30 05:24 UTC, nurisakbar commented
update : 
- Penambahan index
- perubahan dari menyimpan nama menjadi ID

cc : @yohang88

2020-12-01 03:22 UTC, yohang88 approved these changes

2020-12-01 03:22 UTC, merged