add applicant name and event info
jabardigitalservice/pikobar-rapidtest-api pull request #89
Opened 2020-12-03 07:35 UTC by nurisakbar

### overview
penambahan nama peserta, waktu mulai event, waktu berakhir event dan qrcode setelah berhasil mendaftar.
### 
Related Task :
https://trello.com/c/Nk4aXQ0x/173-apabila-peserta-mendaftar-dari-link-kegiatan-yang-sudah-dibuat-di-akhir-pendaftaran-akan-muncul-lokasi-dan-waktu-tesnya
cc : @yohang88

2020-12-04 06:17 UTC, yohang88 requested changes
Cek dulu terkait format tanggal.

2020-12-04 06:17 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtRegisterController.php
> +        Carbon::setLocale(LC_TIME, app()->getLocale());
Ini untuk apa ya?

2020-12-04 06:17 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtRegisterController.php
> +            'event_start_at'    => Carbon::parse($event->start_at)->formatLocalized('%A, %d %B %Y'),
ini kenapa harus pakai format Localized?

Seharusnya penanganan string hari/bulan dalam bahasa Indonesia ditangani di frontend.

2020-12-04 06:19 UTC, nurisakbar commented on app/Http/Controllers/Rdt/RdtRegisterController.php
> +            'event_start_at'    => Carbon::parse($event->start_at)->formatLocalized('%A, %d %B %Y'),
karna tadinya mau di tangani di backend, segera saya ganti kalau gitu

2020-12-07 06:38 UTC, yohang88 commented on app/Http/Controllers/Rdt/RdtRegisterController.php
> +            'event_start_at'    => Carbon::parse($event->start_at)->format('d-m-Y'),
Biasakan format tanggal itu dilakukan di frontend. Backend hanya perlu memberikan response dengan format yang standard (ISO), dan frontend bisa bebas memodifikasi format tampilannya.

2020-12-07 06:55 UTC, yohang88 approved these changes

2020-12-07 06:55 UTC, merged